In [1]:
!pip install geopandas
!pip install tkinter
!pip install vega_datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopandas in /home/s037958714/.local/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: pyproj>=3.3.0 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (3.7.0)
Requirement already satisfied: shapely>=2.0.0 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (2.0.6)
Requirement already satisfied: pyogrio>=0.7.2 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (0.10.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from geopandas) (21.3)
Requirement already satisfied: numpy>=1.22 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (1.25.2)
Requirement already satisfied: pandas>=1.4.0 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (2.1.1)
Requirement already satisfied: tzdata>=2022.1 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=1.4.0->geopandas) (2022.1)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from pyogrio>=0.7.2->geopandas) (2020.6.20)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: vega_datasets in /home/s037958714/.local/lib/python3.10/site-packages (0.9.0)
Requirement already satisfied: pandas in /home/s037958714/.local/lib/python3.10/site-packages (from vega_datasets) (2.1.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->vega_datasets) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas->vega_datasets) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas->vega_datasets) (2023.3)
Requirement already satisfied: numpy>=1.22.4 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas->vega_datasets) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->vega_datasets) (1.16.0)

In [3]:
# =======================================================
# Imports
# =======================================================

import pandas as pd
import numpy as np
import streamlit as st
import altair as alt
from vega_datasets import data

In [4]:
# =======================================================
# Datasets
# =======================================================
df_pessoa_acidentes_2007 = pd.read_csv('../PRF/por_pessoa/acidentes2007.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2008 = pd.read_csv('../PRF/por_pessoa/acidentes2008.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2009 = pd.read_csv('../PRF/por_pessoa/acidentes2009.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2010 = pd.read_csv('../PRF/por_pessoa/acidentes2010.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2011 = pd.read_csv('../PRF/por_pessoa/acidentes2011.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2012 = pd.read_csv('../PRF/por_pessoa/acidentes2012.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2013 = pd.read_csv('../PRF/por_pessoa/acidentes2013.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2014 = pd.read_csv('../PRF/por_pessoa/acidentes2014.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2015 = pd.read_csv('../PRF/por_pessoa/acidentes2015.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2016 = pd.read_csv('../PRF/por_pessoa/acidentes2016.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2017 = pd.read_csv('../PRF/por_pessoa/acidentes2017.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2018 = pd.read_csv('../PRF/por_pessoa/acidentes2018.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2019 = pd.read_csv('../PRF/por_pessoa/acidentes2019.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2020 = pd.read_csv('../PRF/por_pessoa/acidentes2020.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2021 = pd.read_csv('../PRF/por_pessoa/acidentes2021.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2022 = pd.read_csv('../PRF/por_pessoa/acidentes2022.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2023 = pd.read_csv('../PRF/por_pessoa/acidentes2023.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2024 = pd.read_csv('../PRF/por_pessoa/acidentes2024.csv', sep=';', encoding="ISO-8859-1")

/tmp/ipykernel_227769/3339992157.py:4: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2007 = pd.read_csv('../PRF/por_pessoa/acidentes2007.csv', sep=',', encoding="ISO-8859-1")
/tmp/ipykernel_227769/3339992157.py:5: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2008 = pd.read_csv('../PRF/por_pessoa/acidentes2008.csv', sep=',', encoding="ISO-8859-1")
/tmp/ipykernel_227769/3339992157.py:9: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2012 = pd.read_csv('../PRF/por_pessoa/acidentes2012.csv', sep=',', encoding="ISO-8859-1")
/tmp/ipykernel_227769/3339992157.py:14: DtypeWarning: Columns (22,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2017 = pd.read_csv('../PRF/por_pessoa/acidentes2017.csv', sep=';', encoding="ISO-8859-1")

In [14]:
lista_anos = [
    #(2007, df_pessoa_acidentes_2007),
    #(2008, df_pessoa_acidentes_2008),
    #(2009, df_pessoa_acidentes_2009),
    #(2010, df_pessoa_acidentes_2010),
    #(2011, df_pessoa_acidentes_2011),
    #(2012, df_pessoa_acidentes_2012),
    #(2013, df_pessoa_acidentes_2013),
    #(2014, df_pessoa_acidentes_2014),
    #(2015, df_pessoa_acidentes_2015),
    #(2016, df_pessoa_acidentes_2016),
    #(2017, df_pessoa_acidentes_2017),
    #(2018, df_pessoa_acidentes_2018),
    (2019, df_pessoa_acidentes_2019),    
    (2020, df_pessoa_acidentes_2020),
    (2021, df_pessoa_acidentes_2021),
    (2022, df_pessoa_acidentes_2022),
    (2023, df_pessoa_acidentes_2023),
    (2024, df_pessoa_acidentes_2024),
]

In [15]:
for item in lista_anos:
    novo_df = item[1][['data_inversa', 'uf','municipio', 'br', 'km', 'latitude', 'longitude']]
    print(novo_df)
    print(novo_df.isna().sum())
    arquivo = 'geo/acidentes_localizacao_'+str(item[0])+'.csv'
    novo_df.to_csv(arquivo)
    print(f'\nSalvando arquivo arquivo...')

       data_inversa  uf               municipio   br     km     latitude  \
0        2019-01-01  CE                  RUSSAS  116  136,9    -4,766018
1        2019-01-01  MT                AGUA BOA  158  599,5      -14,319
2        2019-01-01  PA              DOM ELISEU   10     34  -4,15296734
3        2019-01-01  BA                RIO REAL  101     13     -11,5896
4        2019-01-01  BA        FEIRA DE SANTANA  116    440      -12,344
...             ...  ..                     ...  ...    ...          ...
176099   2019-10-12  MG              PATROCINIO  365    495   -18,917469
176100   2019-07-20  BA  SANTO ANTONIO DE JESUS  101    263  -12,9785073
176101   2019-07-20  BA  SANTO ANTONIO DE JESUS  101    263  -12,9785073
176102   2019-03-16  BA                  ILHEUS  415     20     -14,8482
176103   2019-03-16  BA                  ILHEUS  415     20     -14,8482

           longitude
0         -38,056034
1            -52,169
2       -47,54608154
3           -37,8761
4            -39,087
...              ...
176099    -47,203773
176100   -39,2841211
176101   -39,2841211
176102    -39,281986
176103    -39,281986

[176104 rows x 7 columns]
data_inversa    0
uf              0
municipio       0
br              0
km              0
latitude        0
longitude       0
dtype: int64

Salvando arquivo arquivo...
       data_inversa  uf              municipio   br     km      latitude  \
0        2020-01-01  PA  SAO FRANCISCO DO PARA  316     84    -1,3101929
1        2020-01-01  PA  SAO FRANCISCO DO PARA  316     84    -1,3101929
2        2020-01-01  MG                UBERABA  262    804  -19,76747537
3        2020-01-01  BA                CANUDOS  116    191  -10,32002103
4        2020-01-01  SP              APARECIDA  116     71  -22,85651665
...             ...  ..                    ...  ...    ...           ...
162247   2020-03-09  SC                  PENHA  101  107,7  -26,82422397
162248   2020-07-18  MG                  PRATA  153   96,4  -19,19257493
162249   2020-09-16  AM               CANUTAMA  319   94,5   -8,41528798
162250   2020-09-16  AM               CANUTAMA  319   94,5   -8,41528798
162251   2020-11-25  BA  GOVERNADOR MANGABEIRA  101    206   -12,6452477

           longitude
0       -47,74456398
1       -47,74456398
2       -47,98725511
3       -39,06425211
4       -45,23114328
...              ...
162247  -48,68853092
162248  -48,94518614
162249  -63,96499613
162250  -63,96499613
162251   -39,1065851

[162252 rows x 7 columns]
data_inversa    0
uf              0
municipio       0
br              0
km              0
latitude        0
longitude       0
dtype: int64

Salvando arquivo arquivo...
       data_inversa  uf                    municipio   br     km  \
0        2021-01-01  SP                     REGISTRO  116    453
1        2021-01-01  AM                       MANAUS  174    937
2        2021-01-01  CE                      ITAPAJE  222  128,5
3        2021-01-01  CE                      ITAPAJE  222  128,5
4        2021-01-01  RJ                         MAGE  493     18
...             ...  ..                          ...  ...    ...
166289   2021-06-27  MG                     MANHUACU  116  577,9
166290   2021-06-27  MG                     MANHUACU  116  577,9
166291   2021-05-07  MT  NOSSA SENHORA DO LIVRAMENTO   70    542
166292   2021-06-05  ES                      ARACRUZ  101  178,4
166293   2021-06-05  ES                      ARACRUZ  101  178,4

            latitude     longitude
0       -24,56168114  -47,86752174
1          -2,508068    -60,036434
2          -3,707626    -39,623509
3          -3,707626    -39,623509
4        -22,6687122  -43,01862696
...              ...           ...
166289  -20,31596699  -42,14564902
166290  -20,31596699  -42,14564902
166291  -15,67915502  -56,31184101
166292  -19,61032522  -40,20858272
166293  -19,61032522  -40,20858272

[166294 rows x 7 columns]
data_inversa    0
uf              0
municipio       0
br              0
km              0
latitude        0
longitude       0
dtype: int64

Salvando arquivo arquivo...
       data_inversa  uf              municipio   br     km      latitude  \
0        2022-01-01  PI            MARCOLANDIA  316    415   -7,43280012
1        2022-01-01  PR  CAMPINA GRANDE DO SUL  116     33    -25,114403
2        2022-01-01  PR  CAMPINA GRANDE DO SUL  116     33    -25,114403
3        2022-01-01  MS   NOVA ALVORADA DO SUL  163    393    -21,228445
4        2022-01-01  RJ         ANGRA DOS REIS  101    457  -23,03149804
...             ...  ..                    ...  ...    ...           ...
170810   2022-01-19  MA             ACAILANDIA  222  638,3     -4,781428
170811   2022-01-19  MA             ACAILANDIA  222  638,3     -4,781428
170812   2022-01-19  MA             ACAILANDIA  222  638,3     -4,781428
170813   2022-01-19  MA             ACAILANDIA  222  638,3     -4,781428
170814   2022-01-19  MA             ACAILANDIA  222  638,3     -4,781428

           longitude
0       -40,68261908
1        -48,8467554
2        -48,8467554
3         -54,456296
4       -44,17715297
...              ...
170810     -47,18019
170811     -47,18019
170812     -47,18019
170813     -47,18019
170814     -47,18019

[170815 rows x 7 columns]
data_inversa    0
uf              0
municipio       0
br              0
km              0
latitude        0
longitude       0
dtype: int64

Salvando arquivo arquivo...
       data_inversa  uf          municipio   br     km      latitude  \
0        2023-01-01  ES          SOORETAMA  101    114  -19,09484877
1        2023-01-01  SP            TAUBATE  116  113,1   -23,0445658
2        2023-01-01  MT  GUARANTA DO NORTE  163   1112   -9,70020602
3        2023-01-01  PR         ORTIGUEIRA  376  314,8    -23,985512
4        2023-01-01  MG           MANHUACU  116  569,4  -20,10007457
...             ...  ..                ...  ...    ...           ...
183350   2023-12-22  PR         ORTIGUEIRA  376    375  -24,41657128
183351   2023-12-22  PR         ORTIGUEIRA  376    375  -24,41657128
183352   2023-12-22  PR         ORTIGUEIRA  376    375  -24,41657128
183353   2023-07-11  PR            MARINGA  376  161,4   -23,3681578
183354   2023-07-11  PR            MARINGA  376  161,4   -23,3681578

           longitude
0       -40,05095848
1       -45,58259814
2       -54,87588757
3         -51,083555
4       -42,17884091
...              ...
183350  -50,78151322
183351  -50,78151322
183352  -50,78151322
183353  -52,06659615
183354  -52,06659615

[183355 rows x 7 columns]
data_inversa    0
uf              0
municipio       0
br              0
km              0
latitude        0
longitude       0
dtype: int64

Salvando arquivo arquivo...
       data_inversa  uf            municipio   br   km      latitude  \
0        2024-01-01  ES   CONCEICAO DA BARRA  101   38     -18,48261
1        2024-01-01  PI             PIRIPIRI  343  185   -4,29603281
2        2024-01-01  BA              BREJOES  116  578  -13,07158302
3        2024-01-01  SE     MALHADA DOS BOIS  101   18  -10,35601949
4        2024-01-01  MT         RONDONOPOLIS  364  240  -16,17914141
...             ...  ..                  ...  ...  ...           ...
128121   2024-07-14  RO  OURO PRETO DO OESTE  364  388  -10,70116422
128122   2024-07-14  RO  OURO PRETO DO OESTE  364  388  -10,70116422
128123   2024-07-14  RO  OURO PRETO DO OESTE  364  388  -10,70116422
128124   2024-07-14  RO  OURO PRETO DO OESTE  364  388  -10,70116422
128125   2024-07-14  RO  OURO PRETO DO OESTE  364  388  -10,70116422

           longitude
0          -39,92379
1       -41,76732659
2        -39,9611107
3       -36,90552235
4       -54,78905337
...              ...
128121  -62,26238327
128122  -62,26238327
128123  -62,26238327
128124  -62,26238327
128125  -62,26238327

[128126 rows x 7 columns]
data_inversa    0
uf              0
municipio       0
br              0
km              0
latitude        0
longitude       0
dtype: int64

Salvando arquivo arquivo...

In [17]:
df_acidentes_geo_2024 = pd.read_csv('geo/acidentes_localizacao_2024.csv', sep=',', encoding="ISO-8859-1")
df_acidentes_geo_2024

,Unnamed: 0,data_inversa,uf,municipio,br,km,latitude,longitude
0,0,2024-01-01,ES,CONCEICAO DA BARRA,101,38,"-18,48261","-39,92379"
1,1,2024-01-01,PI,PIRIPIRI,343,185,"-4,29603281","-41,76732659"
2,2,2024-01-01,BA,BREJOES,116,578,"-13,07158302","-39,9611107"
3,3,2024-01-01,SE,MALHADA DOS BOIS,101,18,"-10,35601949","-36,90552235"
4,4,2024-01-01,MT,RONDONOPOLIS,364,240,"-16,17914141","-54,78905337"
...,...,...,...,...,...,...,...,...
128121,128121,2024-07-14,RO,OURO PRETO DO OESTE,364,388,"-10,70116422","-62,26238327"
128122,128122,2024-07-14,RO,OURO PRETO DO OESTE,364,388,"-10,70116422","-62,26238327"
128123,128123,2024-07-14,RO,OURO PRETO DO OESTE,364,388,"-10,70116422","-62,26238327"
128124,128124,2024-07-14,RO,OURO PRETO DO OESTE,364,388,"-10,70116422","-62,26238327"
128125,128125,2024-07-14,RO,OURO PRETO DO OESTE,364,388,"-10,70116422","-62,26238327"

In [46]:
#df_filtrado_uf = df_uf[(df_uf['UF'] == item)]
#df_acidentes_geo_2024_br_101 = df_acidentes_geo_2024[(df_acidentes_geo_2024['br'] == 101)]
#df_acidentes_geo_2024_br_101
subconjunto = df_acidentes_geo_2024.query("br == 101 and km == '733'")
subconjunto

       Unnamed: 0 data_inversa  uf municipio   br   km    latitude   longitude
17             17   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
18             18   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
28239       28239   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
28240       28240   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
28241       28241   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
28242       28242   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
28243       28243   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433
28244       28244   2024-01-01  BA   ITABELA  101  733  -16,489273  -39,577433

In [45]:
subconjunto = df_acidentes_geo_2024.query("br == 101 and km == '733'")
subconjunto['latitude'] = subconjunto['latitude'].str.replace(',', '.')
subconjunto['longitude'] = subconjunto['longitude'].str.replace(',', '.')

#grouped_df = df.groupby('Category')['Value'].sum()
#print(grouped_df)
subconjunto.to_csv('geo/acidentes_localizacao_2024_br_101_km_733.csv',sep=';')

/tmp/ipykernel_227769/230783708.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subconjunto['latitude'] = subconjunto['latitude'].str.replace(',', '.')
/tmp/ipykernel_227769/230783708.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subconjunto['longitude'] = subconjunto['longitude'].str.replace(',', '.')

In [47]:
df_semaforos = pd.read_csv('geo/acidentes_localizacao_2024_br_101_km_733.csv', sep=';', decimal='.')
df_semaforos
# Aplicar a função para criar a nova coluna 'cor'
#df_semaforos['cor'] = df_semaforos[coluna_dados].apply(definir_cor)
#df['Column1'] = df['Column1'].str.replace(',', '.')

,Unnamed: 0.1,Unnamed: 0,data_inversa,uf,municipio,br,km,latitude,longitude
0,17,17,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
1,18,18,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
2,28239,28239,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
3,28240,28240,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
4,28241,28241,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
5,28242,28242,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
6,28243,28243,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433
7,28244,28244,2024-01-01,BA,ITABELA,101,733,-16.489273,-39.577433

In [48]:
st.map(df_semaforos,
    latitude='latitude',
    longitude='longitude',
    size=10,
    color='#FF0000',
    use_container_width=False)

DeltaGenerator()

In [6]:
# =======================================================
# Funções
# =======================================================
def agrupamento_acidentes_por_ano_por_uf(df):
  contagem_por_uf = df['uf'].value_counts().reset_index()
  contagem_por_uf.columns = ['UF', 'Qtd']
  return contagem_por_uf
# =======================================================
def agrupamento_acidentes_por_ano_por_br(df):
  contagem_por_br = df['br'].value_counts().reset_index()
  contagem_por_br.columns = ['br', 'qtd']
  return contagem_por_br
# =======================================================
def agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes):
  contagem_por_tipo = df_ocorrencia_acidentes['tipo_acidente'].value_counts().reset_index()
  contagem_por_tipo.columns = ['tipo_acidente', 'qtd']
  return contagem_por_tipo
# =======================================================  
def agrupamento_acidentes_por_ano_por_causa(df):
  contagem_por_causa = df['causa_acidente'].value_counts().reset_index()
  contagem_por_causa.columns = ['causa_acidente', 'qtd']
  return contagem_por_causa    
# =======================================================
def agrupamento_acidentes_por_ano_por_classificacao(df):
  contagem_por_classificacao = df['classificacao_acidente'].value_counts().reset_index()
  contagem_por_classificacao.columns = ['classificacao_acidente', 'qtd']
  return contagem_por_classificacao    
# =======================================================
def agrupamento_acidentes_por_ano_por_fase_dia(df):
  contagem_por_fase_dia = df['fase_dia'].value_counts().reset_index(name='qtd')
  contagem_por_fase_dia.columns = ['fase_dia', 'qtd']
  return contagem_por_fase_dia    
# =======================================================
def agrupamento_acidentes_por_ano_por_condicao_metereologica(df):
  contagem_por_condicao_meteorologica = df['condicao_metereologica'].value_counts().reset_index(name='qtd')
  contagem_por_condicao_meteorologica.columns = ['condicao_metereologica', 'qtd']
  return contagem_por_condicao_meteorologica       
# =======================================================
def processa_acidentes_geral_ufs():
    
    contagem_por_uf_2007 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2007)
    contagem_por_uf_2008 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2008)
    contagem_por_uf_2009 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2009)
    contagem_por_uf_2010 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2010)
    contagem_por_uf_2011 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2011)
    contagem_por_uf_2012 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2012)
    contagem_por_uf_2013 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2013)
    contagem_por_uf_2014 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2014)
    contagem_por_uf_2015 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2015)
    contagem_por_uf_2016 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2016)
    contagem_por_uf_2017 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2017)
    contagem_por_uf_2018 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2018)
    contagem_por_uf_2019 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2019)
    contagem_por_uf_2020 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2020)
    contagem_por_uf_2021 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2021)
    contagem_por_uf_2022 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2022)
    contagem_por_uf_2023 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2023)
    contagem_por_uf_2024 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2024)
    
    contagem_por_uf_2007['ano'] = '2007'
    contagem_por_uf_2008['ano'] = '2008'
    contagem_por_uf_2009['ano'] = '2009'
    contagem_por_uf_2010['ano'] = '2010'
    contagem_por_uf_2011['ano'] = '2011'
    contagem_por_uf_2012['ano'] = '2012'
    contagem_por_uf_2013['ano'] = '2013'
    contagem_por_uf_2014['ano'] = '2014'
    contagem_por_uf_2015['ano'] = '2015'
    contagem_por_uf_2016['ano'] = '2016'
    contagem_por_uf_2017['ano'] = '2017'
    contagem_por_uf_2018['ano'] = '2018'
    contagem_por_uf_2019['ano'] = '2019'
    contagem_por_uf_2020['ano'] = '2020'
    contagem_por_uf_2021['ano'] = '2021'
    contagem_por_uf_2022['ano'] = '2022'
    contagem_por_uf_2023['ano'] = '2023'
    contagem_por_uf_2024['ano'] = '2024'

    acidentes_por_uf_concatenados = pd.concat(
    [
      contagem_por_uf_2007, contagem_por_uf_2008, contagem_por_uf_2009,
      contagem_por_uf_2010, contagem_por_uf_2011, contagem_por_uf_2012,
      contagem_por_uf_2013, contagem_por_uf_2014, contagem_por_uf_2015,
      contagem_por_uf_2016, contagem_por_uf_2017, contagem_por_uf_2018,
      contagem_por_uf_2019, contagem_por_uf_2020, contagem_por_uf_2021,
      contagem_por_uf_2022, contagem_por_uf_2023, contagem_por_uf_2024
    
    ], axis=0)
    
    lista_ufs = []
    
    for item in acidentes_por_uf_concatenados['UF'].unique():
      lista_ufs.append(item)
    lista_ufs.remove('(null)')
    
    lista_ufs = lista_ufs[:10]
    df_uf = acidentes_por_uf_concatenados
    df_geral_uf = pd.DataFrame(columns=['UF','Qtd','ano'])
    
    for item in lista_ufs:
      df_filtrado_uf = df_uf[(df_uf['UF'] == item)]
      df_geral_uf = pd.concat([df_geral_uf, df_filtrado_uf], ignore_index=True)
        
    df_geral_uf.to_csv('acidentes_geral_por_uf.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_uf...')

    return df_geral_uf
# =======================================================
def processa_acidentes_geral_tipo():

    df_ocorrencia_acidentes_2007 = pd.read_csv('../PRF/por_ocorrencia/datatran2007.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2008 = pd.read_csv('../PRF/por_ocorrencia/datatran2008.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2009 = pd.read_csv('../PRF/por_ocorrencia/datatran2009.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2010 = pd.read_csv('../PRF/por_ocorrencia/datatran2010.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2011 = pd.read_csv('../PRF/por_ocorrencia/datatran2011.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2012 = pd.read_csv('../PRF/por_ocorrencia/datatran2012.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2013 = pd.read_csv('../PRF/por_ocorrencia/datatran2013.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2014 = pd.read_csv('../PRF/por_ocorrencia/datatran2014.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2015 = pd.read_csv('../PRF/por_ocorrencia/datatran2015.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2016 = pd.read_csv('../PRF/por_ocorrencia/datatran2016.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2017 = pd.read_csv('../PRF/por_ocorrencia/datatran2017.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2018 = pd.read_csv('../PRF/por_ocorrencia/datatran2018.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2019 = pd.read_csv('../PRF/por_ocorrencia/datatran2019.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2020 = pd.read_csv('../PRF/por_ocorrencia/datatran2020.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2021 = pd.read_csv('../PRF/por_ocorrencia/datatran2021.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2022 = pd.read_csv('../PRF/por_ocorrencia/datatran2022.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2023 = pd.read_csv('../PRF/por_ocorrencia/datatran2023.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2024 = pd.read_csv('../PRF/por_ocorrencia/datatran2024.csv', sep=';', encoding="ISO-8859-1", low_memory=False)

    contagem_por_tipo_2007 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2007)
    contagem_por_tipo_2008 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2008)
    contagem_por_tipo_2009 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2009)
    contagem_por_tipo_2010 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2010)
    contagem_por_tipo_2011 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2011)
    contagem_por_tipo_2012 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2012)
    contagem_por_tipo_2013 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2013)
    contagem_por_tipo_2014 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2014)
    contagem_por_tipo_2015 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2015)
    contagem_por_tipo_2016 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2016)
    contagem_por_tipo_2017 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2017)
    contagem_por_tipo_2018 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2018)
    contagem_por_tipo_2019 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2019)
    contagem_por_tipo_2020 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2020)
    contagem_por_tipo_2021 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2021)
    contagem_por_tipo_2022 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2022)
    contagem_por_tipo_2023 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2023)
    contagem_por_tipo_2024 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2024)
    
    contagem_por_tipo_2007['ano'] = '2007'
    contagem_por_tipo_2008['ano'] = '2008'
    contagem_por_tipo_2009['ano'] = '2009'
    contagem_por_tipo_2010['ano'] = '2010'
    contagem_por_tipo_2011['ano'] = '2011'
    contagem_por_tipo_2012['ano'] = '2012'
    contagem_por_tipo_2013['ano'] = '2013'
    contagem_por_tipo_2014['ano'] = '2014'
    contagem_por_tipo_2015['ano'] = '2015'
    contagem_por_tipo_2016['ano'] = '2016'
    contagem_por_tipo_2017['ano'] = '2017'
    contagem_por_tipo_2018['ano'] = '2018'
    contagem_por_tipo_2019['ano'] = '2019'
    contagem_por_tipo_2020['ano'] = '2020'
    contagem_por_tipo_2021['ano'] = '2021'
    contagem_por_tipo_2022['ano'] = '2022'
    contagem_por_tipo_2023['ano'] = '2023'
    contagem_por_tipo_2024['ano'] = '2024'
    
    
    acidentes_por_tipo_concatenados = pd.concat(
    [
        contagem_por_tipo_2007, contagem_por_tipo_2008, contagem_por_tipo_2009,
        contagem_por_tipo_2010, contagem_por_tipo_2011, contagem_por_tipo_2012,
        contagem_por_tipo_2013, contagem_por_tipo_2014, contagem_por_tipo_2015,
        contagem_por_tipo_2016, contagem_por_tipo_2017, contagem_por_tipo_2018,
        contagem_por_tipo_2019, contagem_por_tipo_2020, contagem_por_tipo_2021,
        contagem_por_tipo_2022, contagem_por_tipo_2023, contagem_por_tipo_2024
    
    ], axis=0)
    
    acidentes_por_tipo_concatenados
    
    df_tipo = acidentes_por_tipo_concatenados
    df_geral_tipo = pd.DataFrame(columns=['tipo_acidente','qtd','ano'])

    lista_acidentes = contagem_por_tipo_2023['tipo_acidente'].unique()
    lista_acidentes = lista_acidentes[:15]
    lista_acidentes
    
    for item in lista_acidentes:
      df_filtrado_tipo = df_tipo[(df_tipo['tipo_acidente'] == item)]
      df_geral_tipo = pd.concat([df_geral_tipo, df_filtrado_tipo], ignore_index=True)
    
    df_geral_tipo
    
    df_geral_tipo.to_csv('acidentes_geral_por_tipo.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_tipo.csv...')
    
    return df_geral_tipo
# =======================================================
def processa_acidentes_geral_br():

    acidentes_br_2007 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2007)
    acidentes_br_2008 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2008)
    acidentes_br_2009 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2009)
    acidentes_br_2010 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2010)
    acidentes_br_2011 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2011)
    acidentes_br_2012 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2012)
    acidentes_br_2013 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2013)
    acidentes_br_2014 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2014)
    acidentes_br_2015 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2015)
    acidentes_br_2016 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2016)
    acidentes_br_2017 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2017)
    acidentes_br_2018 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2018)
    acidentes_br_2019 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2019)
    acidentes_br_2020 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2020)
    acidentes_br_2021 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2021)
    acidentes_br_2022 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2022)
    acidentes_br_2023 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2023)
    acidentes_br_2024 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2024)   
   
    acidentes_br_2007['ano'] = '2007'
    acidentes_br_2008['ano'] = '2008'
    acidentes_br_2009['ano'] = '2009'
    acidentes_br_2010['ano'] = '2010'
    acidentes_br_2011['ano'] = '2011'
    acidentes_br_2012['ano'] = '2012'
    acidentes_br_2013['ano'] = '2013'
    acidentes_br_2014['ano'] = '2014'
    acidentes_br_2015['ano'] = '2015'
    acidentes_br_2016['ano'] = '2016'
    acidentes_br_2017['ano'] = '2017'
    acidentes_br_2018['ano'] = '2018'
    acidentes_br_2019['ano'] = '2019'
    acidentes_br_2020['ano'] = '2020'
    acidentes_br_2021['ano'] = '2021'
    acidentes_br_2022['ano'] = '2022'
    acidentes_br_2023['ano'] = '2023'
    acidentes_br_2024['ano'] = '2024'
    
    acidentes_brs_concatenados = pd.concat(
    [
        acidentes_br_2007, acidentes_br_2008, acidentes_br_2009,
        acidentes_br_2010, acidentes_br_2011, acidentes_br_2012,
        acidentes_br_2013, acidentes_br_2014, acidentes_br_2015,
        acidentes_br_2016, acidentes_br_2017, acidentes_br_2018,
        acidentes_br_2019, acidentes_br_2020, acidentes_br_2021,
        acidentes_br_2022, acidentes_br_2023, acidentes_br_2024
    ], axis=0)
    
    acidentes_brs_concatenados
    
    lista_brs = ['101','116','381','40','153','163','364','227','376','262','230','470','316','282','70','60','20','158','369','50']
    
    df = acidentes_brs_concatenados
    df_geral_br = pd.DataFrame(columns=['br', 'qtd', 'ano'])
    
    for item in lista_brs:
      df_filtrado_br = df[(df['br'] == int(item))]
      df_geral_br = pd.concat([df_geral_br, df_filtrado_br], ignore_index=True)

    df_geral_br
    df_geral_br.to_csv('acidentes_geral_por_br.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_br.csv...')
    
    return df_geral_br   
# =======================================================
def processa_acidentes_geral_causa():
    
    contagem_por_causa_2007 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2007)
    contagem_por_causa_2008 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2008)
    contagem_por_causa_2009 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2009)
    contagem_por_causa_2010 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2010)
    contagem_por_causa_2011 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2011)
    contagem_por_causa_2012 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2012)
    contagem_por_causa_2013 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2013)
    contagem_por_causa_2014 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2014)
    contagem_por_causa_2015 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2015)
    contagem_por_causa_2016 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2016)
    contagem_por_causa_2017 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2017)
    contagem_por_causa_2018 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2018)
    contagem_por_causa_2019 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2019)
    contagem_por_causa_2020 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2020)
    contagem_por_causa_2021 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2021)
    contagem_por_causa_2022 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2022)
    contagem_por_causa_2023 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2023)
    contagem_por_causa_2024 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2024)
    
    contagem_por_causa_2007['ano'] = '2007'
    contagem_por_causa_2008['ano'] = '2008'
    contagem_por_causa_2009['ano'] = '2009'
    contagem_por_causa_2010['ano'] = '2010'
    contagem_por_causa_2011['ano'] = '2011'
    contagem_por_causa_2012['ano'] = '2012'
    contagem_por_causa_2013['ano'] = '2013'
    contagem_por_causa_2014['ano'] = '2014'
    contagem_por_causa_2015['ano'] = '2015'
    contagem_por_causa_2016['ano'] = '2016'
    contagem_por_causa_2017['ano'] = '2017'
    contagem_por_causa_2018['ano'] = '2018'
    contagem_por_causa_2019['ano'] = '2019'
    contagem_por_causa_2020['ano'] = '2020'
    contagem_por_causa_2021['ano'] = '2021'
    contagem_por_causa_2022['ano'] = '2022'
    contagem_por_causa_2023['ano'] = '2023'
    contagem_por_causa_2024['ano'] = '2024'

    acidentes_por_causa_concatenados = pd.concat(
    [
      contagem_por_causa_2007, contagem_por_causa_2008, contagem_por_causa_2009,
      contagem_por_causa_2010, contagem_por_causa_2011, contagem_por_causa_2012,
      contagem_por_causa_2013, contagem_por_causa_2014, contagem_por_causa_2015,
      contagem_por_causa_2016, contagem_por_causa_2017, contagem_por_causa_2018,
      contagem_por_causa_2019, contagem_por_causa_2020, contagem_por_causa_2021,
      contagem_por_causa_2022, contagem_por_causa_2023, contagem_por_causa_2024
    
    ], axis=0)
    
    lista_causas = []
    
    for item in acidentes_por_causa_concatenados['causa_acidente'].unique():
      lista_causas.append(item)
    lista_causas.remove('(null)')
    
    lista_causas = lista_causas[:25]
    
    df_causa = acidentes_por_causa_concatenados
    df_geral_causa = pd.DataFrame(columns=['causa_acidente','qtd','ano'])
    
    for item in lista_causas:
      df_filtrado_causa = df_causa[(df_causa['causa_acidente'] == item)]
      df_geral_causa = pd.concat([df_geral_causa, df_filtrado_causa], ignore_index=True)
        
    df_geral_causa.to_csv('acidentes_geral_por_causa.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_causa.csv...')

    return df_geral_causa
# =======================================================
def processa_acidentes_geral_classificacao():
    
    contagem_por_classificacao_2007 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2007)
    contagem_por_classificacao_2008 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2008)
    contagem_por_classificacao_2009 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2009)
    contagem_por_classificacao_2010 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2010)
    contagem_por_classificacao_2011 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2011)
    contagem_por_classificacao_2012 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2012)
    contagem_por_classificacao_2013 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2013)
    contagem_por_classificacao_2014 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2014)
    contagem_por_classificacao_2015 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2015)
    contagem_por_classificacao_2016 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2016)
    contagem_por_classificacao_2017 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2017)
    contagem_por_classificacao_2018 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2018)
    contagem_por_classificacao_2019 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2019)
    contagem_por_classificacao_2020 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2020)
    contagem_por_classificacao_2021 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2021)
    contagem_por_classificacao_2022 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2022)
    contagem_por_classificacao_2023 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2023)
    contagem_por_classificacao_2024 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2024)
    
    contagem_por_classificacao_2007['ano'] = '2007'
    contagem_por_classificacao_2008['ano'] = '2008'
    contagem_por_classificacao_2009['ano'] = '2009'
    contagem_por_classificacao_2010['ano'] = '2010'
    contagem_por_classificacao_2011['ano'] = '2011'
    contagem_por_classificacao_2012['ano'] = '2012'
    contagem_por_classificacao_2013['ano'] = '2013'
    contagem_por_classificacao_2014['ano'] = '2014'
    contagem_por_classificacao_2015['ano'] = '2015'
    contagem_por_classificacao_2016['ano'] = '2016'
    contagem_por_classificacao_2017['ano'] = '2017'
    contagem_por_classificacao_2018['ano'] = '2018'
    contagem_por_classificacao_2019['ano'] = '2019'
    contagem_por_classificacao_2020['ano'] = '2020'
    contagem_por_classificacao_2021['ano'] = '2021'
    contagem_por_classificacao_2022['ano'] = '2022'
    contagem_por_classificacao_2023['ano'] = '2023'
    contagem_por_classificacao_2024['ano'] = '2024'

    acidentes_por_classificacao_concatenados = pd.concat(
    [
      contagem_por_classificacao_2007, contagem_por_classificacao_2008, contagem_por_classificacao_2009,
      contagem_por_classificacao_2010, contagem_por_classificacao_2011, contagem_por_classificacao_2012,
      contagem_por_classificacao_2013, contagem_por_classificacao_2014, contagem_por_classificacao_2015,
      contagem_por_classificacao_2016, contagem_por_classificacao_2017, contagem_por_classificacao_2018,
      contagem_por_classificacao_2019, contagem_por_classificacao_2020, contagem_por_classificacao_2021,
      contagem_por_classificacao_2022, contagem_por_classificacao_2023, contagem_por_classificacao_2024
    
    ], axis=0)
    
    lista_classificacoes_antes = acidentes_por_classificacao_concatenados['classificacao_acidente'].unique()
    print(f'lista_classificacoes_antes => {lista_classificacoes_antes}')
    
    lista_classificacoes_depois = [item.rstrip() for item in lista_classificacoes_antes]
    lista_classificacoes_depois.remove('(null)')
    
    print(f'lista_classificacoes_depois => {lista_classificacoes_depois}')
    
    lista_sem_duplicacacoes = list(set(lista_classificacoes_depois))
    print(f'lista_sem_duplicacacoes => {lista_sem_duplicacacoes}')
    
    
    lista_classificacoes = lista_sem_duplicacacoes
    
    print(f'lista_classificacoes => {lista_classificacoes} ')
    
    df_classificacao = acidentes_por_classificacao_concatenados
    df_geral_classificacao = pd.DataFrame(columns=['classificacao_acidente','qtd','ano'])
    
    for item in lista_classificacoes:
      df_filtrado_classificacao = df_classificacao[(df_classificacao['classificacao_acidente'] == item)]
      df_geral_classificacao = pd.concat([df_geral_classificacao, df_filtrado_classificacao], ignore_index=True)
    
    df_geral_classificacao.to_csv('acidentes_geral_por_classificacao.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_classificacao.csv...')
    
    return df_geral_classificacao   
# =======================================================
def processa_acidentes_geral_fase_dia():
    
    contagem_por_fase_dia_2007 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2007)
    contagem_por_fase_dia_2008 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2008)
    contagem_por_fase_dia_2009 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2009)
    contagem_por_fase_dia_2010 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2010)
    contagem_por_fase_dia_2011 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2011)
    contagem_por_fase_dia_2012 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2012)
    contagem_por_fase_dia_2013 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2013)
    contagem_por_fase_dia_2014 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2014)
    contagem_por_fase_dia_2015 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2015)
    contagem_por_fase_dia_2016 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2016)
    contagem_por_fase_dia_2017 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2017)
    contagem_por_fase_dia_2018 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2018)
    contagem_por_fase_dia_2019 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2019)
    contagem_por_fase_dia_2020 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2020)
    contagem_por_fase_dia_2021 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2021)
    contagem_por_fase_dia_2022 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2022)
    contagem_por_fase_dia_2023 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2023)
    contagem_por_fase_dia_2024 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2024)
    
    contagem_por_fase_dia_2007['ano'] = '2007'
    contagem_por_fase_dia_2008['ano'] = '2008'
    contagem_por_fase_dia_2009['ano'] = '2009'
    contagem_por_fase_dia_2010['ano'] = '2010'
    contagem_por_fase_dia_2011['ano'] = '2011'
    contagem_por_fase_dia_2012['ano'] = '2012'
    contagem_por_fase_dia_2013['ano'] = '2013'
    contagem_por_fase_dia_2014['ano'] = '2014'
    contagem_por_fase_dia_2015['ano'] = '2015'
    contagem_por_fase_dia_2016['ano'] = '2016'
    contagem_por_fase_dia_2017['ano'] = '2017'
    contagem_por_fase_dia_2018['ano'] = '2018'
    contagem_por_fase_dia_2019['ano'] = '2019'
    contagem_por_fase_dia_2020['ano'] = '2020'
    contagem_por_fase_dia_2021['ano'] = '2021'
    contagem_por_fase_dia_2022['ano'] = '2022'
    contagem_por_fase_dia_2023['ano'] = '2023'
    contagem_por_fase_dia_2024['ano'] = '2024'

    acidentes_por_fase_dia_concatenados = pd.concat(
    [
      contagem_por_fase_dia_2007, contagem_por_fase_dia_2008, contagem_por_fase_dia_2009,
      contagem_por_fase_dia_2010, contagem_por_fase_dia_2011, contagem_por_fase_dia_2012,
      contagem_por_fase_dia_2013, contagem_por_fase_dia_2014, contagem_por_fase_dia_2015,
      contagem_por_fase_dia_2016, contagem_por_fase_dia_2017, contagem_por_fase_dia_2018,
      contagem_por_fase_dia_2019, contagem_por_fase_dia_2020, contagem_por_fase_dia_2021,
      contagem_por_fase_dia_2022, contagem_por_fase_dia_2023, contagem_por_fase_dia_2024
    
    ], axis=0)
    
    lista_fases = []
    
    for item in acidentes_por_fase_dia_concatenados['fase_dia'].unique():
      lista_fases.append(item)
    lista_fases.remove('(null)')
        
    df_fase = acidentes_por_fase_dia_concatenados
    df_geral_fase_dia = pd.DataFrame(columns=['fase_dia','qtd','ano'])
    
    for item in lista_fases:
      df_filtrado_fase = df_fase[(df_fase['fase_dia'] == item)]
      df_geral_fase_dia = pd.concat([df_geral_fase_dia, df_filtrado_fase], ignore_index=True)
        
    df_geral_fase_dia.to_csv('acidentes_geral_por_fase_dia.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_fase_dia.csv...')

    return df_geral_fase_dia  
# =======================================================
def processa_acidentes_geral_condicao_metereologica():

    contagem_por_condicao_metereologica_2007 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2007)
    contagem_por_condicao_metereologica_2008 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2008)
    contagem_por_condicao_metereologica_2009 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2009)
    contagem_por_condicao_metereologica_2010 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2010)
    contagem_por_condicao_metereologica_2011 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2011)
    contagem_por_condicao_metereologica_2012 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2012)
    contagem_por_condicao_metereologica_2013 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2013)
    contagem_por_condicao_metereologica_2014 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2014)
    contagem_por_condicao_metereologica_2015 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2015)
    contagem_por_condicao_metereologica_2016 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2016)
    contagem_por_condicao_metereologica_2017 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2017)
    contagem_por_condicao_metereologica_2018 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2018)
    contagem_por_condicao_metereologica_2019 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2019)
    contagem_por_condicao_metereologica_2020 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2020)
    contagem_por_condicao_metereologica_2021 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2021)
    contagem_por_condicao_metereologica_2022 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2022)
    contagem_por_condicao_metereologica_2023 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2023)
    contagem_por_condicao_metereologica_2024 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2024)
    
    contagem_por_condicao_metereologica_2007['ano'] = '2007'
    contagem_por_condicao_metereologica_2008['ano'] = '2008'
    contagem_por_condicao_metereologica_2009['ano'] = '2009'
    contagem_por_condicao_metereologica_2010['ano'] = '2010'
    contagem_por_condicao_metereologica_2011['ano'] = '2011'
    contagem_por_condicao_metereologica_2012['ano'] = '2012'
    contagem_por_condicao_metereologica_2013['ano'] = '2013'
    contagem_por_condicao_metereologica_2014['ano'] = '2014'
    contagem_por_condicao_metereologica_2015['ano'] = '2015'
    contagem_por_condicao_metereologica_2016['ano'] = '2016'
    contagem_por_condicao_metereologica_2017['ano'] = '2017'
    contagem_por_condicao_metereologica_2018['ano'] = '2018'
    contagem_por_condicao_metereologica_2019['ano'] = '2019'
    contagem_por_condicao_metereologica_2020['ano'] = '2020'
    contagem_por_condicao_metereologica_2021['ano'] = '2021'
    contagem_por_condicao_metereologica_2022['ano'] = '2022'
    contagem_por_condicao_metereologica_2023['ano'] = '2023'
    contagem_por_condicao_metereologica_2024['ano'] = '2024'

    acidentes_por_condicao_metereologica_concatenados = pd.concat(
    [
      contagem_por_condicao_metereologica_2007, contagem_por_condicao_metereologica_2008, contagem_por_condicao_metereologica_2009,
      contagem_por_condicao_metereologica_2010, contagem_por_condicao_metereologica_2011, contagem_por_condicao_metereologica_2012,
      contagem_por_condicao_metereologica_2013, contagem_por_condicao_metereologica_2014, contagem_por_condicao_metereologica_2015,
      contagem_por_condicao_metereologica_2016, contagem_por_condicao_metereologica_2017, contagem_por_condicao_metereologica_2018,
      contagem_por_condicao_metereologica_2019, contagem_por_condicao_metereologica_2020, contagem_por_condicao_metereologica_2021,
      contagem_por_condicao_metereologica_2022, contagem_por_condicao_metereologica_2023, contagem_por_condicao_metereologica_2024
    
    ], axis=0)
    
    lista_condicoes = []
    
    for item in acidentes_por_condicao_metereologica_concatenados['condicao_metereologica'].unique():
      lista_condicoes.append(item)
   
    df_condicao = acidentes_por_condicao_metereologica_concatenados
    df_geral_condicao_metereologica = pd.DataFrame(columns=['condicao_metereologica','qtd','ano'])
    
    for item in lista_condicoes:
      df_filtrado_classificacao = df_condicao[(df_condicao['condicao_metereologica'] == item)]
      df_geral_condicao_metereologica = pd.concat([df_geral_condicao_metereologica, df_filtrado_classificacao], ignore_index=True)
        
    df_geral_condicao_metereologica.to_csv('acidentes_geral_por_condicao_metereologica.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_condicao_metereologica.csv...')

    return df_geral_condicao_metereologica   
# =======================================================
def gera_grafico_por_uf(titulo, contagem_por_uf_ano):

  lista_cores = alt.Scale(domain= contagem_por_uf_ano['UF'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart_uf = alt.Chart(contagem_por_uf_ano).mark_bar().encode(
      y=alt.Y('UF:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('Qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['UF', 'Qtd'],
      color=alt.Color('UF:N', scale=lista_cores)

  ).properties(
      title=alt.Title(
        text=titulo  
      ),
      width=800
  ).interactive()

  return chart_uf
# =======================================================
def gera_grafico_por_tipo(titulo, contagem_por_tipo_ano):

  lista_cores = alt.Scale(domain=contagem_por_tipo_ano['tipo_acidente'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart_tipo = alt.Chart(contagem_por_tipo_ano).mark_bar().encode(
      y=alt.Y('tipo_acidente:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['tipo_acidente', 'qtd'],
      color=alt.Color('tipo_acidente:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600           
  ).interactive()

  return chart_tipo
# =======================================================
def gera_grafico_barras_horizontal_por_br(titulo, contagem_por_br_ano):

  lista_cores = alt.Scale(domain=contagem_por_br_ano['br'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart_br = alt.Chart(contagem_por_br_ano).mark_bar().encode(
      y=alt.Y('br:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['br', 'qtd'],
      color=alt.Color('br:N', scale=lista_cores)

  ).properties(
      title=titulo
  ).interactive()

  return chart_br
# =======================================================
def gera_grafico_por_causa(titulo, contagem_por_causa_ano):

  lista_cores = alt.Scale(domain=contagem_por_causa_ano['causa_acidente'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_causa_ano).mark_bar().encode(
      y=alt.Y('causa_acidente:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['causa_acidente', 'qtd'],
      color=alt.Color('causa_acidente:N', scale=lista_cores)

  ).properties(
      #title=f'Acidentes por Causa no Ano de {ano}',
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart

# =======================================================
def gera_grafico_por_classificacao(titulo, contagem_por_classificacao_ano):

  lista_cores = alt.Scale(domain=contagem_por_classificacao_ano['classificacao_acidente'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_classificacao_ano).mark_bar().encode(
      y=alt.Y('classificacao_acidente:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['classificacao_acidente', 'qtd'],
      color=alt.Color('classificacao_acidente:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart
# =======================================================
def gera_grafico_por_fase_dia(titulo, contagem_por_fase_dia):

  lista_cores = alt.Scale(domain=contagem_por_fase_dia['fase_dia'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_fase_dia).mark_bar().encode(
      y=alt.Y('fase_dia:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['fase_dia', 'qtd'],
      color=alt.Color('fase_dia:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart
# =======================================================
def gera_grafico_por_condicao_metereologica(titulo, contagem_por_condicao_metereologica):

  lista_cores = alt.Scale(domain=contagem_por_condicao_metereologica['condicao_metereologica'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_condicao_metereologica).mark_bar().encode(
      y=alt.Y('condicao_metereologica:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['condicao_metereologica', 'qtd'],
      color=alt.Color('condicao_metereologica:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart

In [41]:
df_geral_classificacao = pd.DataFrame(columns=['classificacao','pessoas','mortos','feridos_leves','feridos_graves','ilesos','ignorados','feridos','veiculos'])
df_geral_classificacao

Empty DataFrame
Columns: [classificacao, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos]
Index: []