In [1]:
!pip install geopandas
!pip install tkinter
!pip install vega_datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopandas in /home/s037958714/.local/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: pyproj>=3.3.0 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (3.7.0)
Requirement already satisfied: pandas>=1.4.0 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (2.1.1)
Requirement already satisfied: pyogrio>=0.7.2 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (0.10.0)
Requirement already satisfied: numpy>=1.22 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (1.25.2)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from geopandas) (21.3)
Requirement already satisfied: shapely>=2.0.0 in /home/s037958714/.local/lib/python3.10/site-packages (from geopandas) (2.0.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=1.4.0->geopandas) (2022.1)
Requirement already satisfied: tzdata>=2022.1 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2023.3)
Requirement already satisfied: certifi in /home/s037958714/.local/lib/python3.10/site-packages (from pyogrio>=0.7.2->geopandas) (2024.8.30)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: vega_datasets in /home/s037958714/.local/lib/python3.10/site-packages (0.9.0)
Requirement already satisfied: pandas in /home/s037958714/.local/lib/python3.10/site-packages (from vega_datasets) (2.1.1)
Requirement already satisfied: tzdata>=2022.1 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas->vega_datasets) (2023.3)
Requirement already satisfied: numpy>=1.22.4 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas->vega_datasets) (1.25.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->vega_datasets) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/s037958714/.local/lib/python3.10/site-packages (from pandas->vega_datasets) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->vega_datasets) (1.16.0)

In [1]:
# =======================================================
# Imports
# =======================================================

import pandas as pd
import numpy as np
import streamlit as st
import altair as alt
from vega_datasets import data

In [2]:
# =======================================================
# Datasets
# =======================================================
df_pessoa_acidentes_2007 = pd.read_csv('../PRF/por_pessoa/acidentes2007.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2008 = pd.read_csv('../PRF/por_pessoa/acidentes2008.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2009 = pd.read_csv('../PRF/por_pessoa/acidentes2009.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2010 = pd.read_csv('../PRF/por_pessoa/acidentes2010.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2011 = pd.read_csv('../PRF/por_pessoa/acidentes2011.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2012 = pd.read_csv('../PRF/por_pessoa/acidentes2012.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2013 = pd.read_csv('../PRF/por_pessoa/acidentes2013.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2014 = pd.read_csv('../PRF/por_pessoa/acidentes2014.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2015 = pd.read_csv('../PRF/por_pessoa/acidentes2015.csv', sep=',', encoding="ISO-8859-1")
df_pessoa_acidentes_2016 = pd.read_csv('../PRF/por_pessoa/acidentes2016.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2017 = pd.read_csv('../PRF/por_pessoa/acidentes2017.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2018 = pd.read_csv('../PRF/por_pessoa/acidentes2018.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2019 = pd.read_csv('../PRF/por_pessoa/acidentes2019.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2020 = pd.read_csv('../PRF/por_pessoa/acidentes2020.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2021 = pd.read_csv('../PRF/por_pessoa/acidentes2021.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2022 = pd.read_csv('../PRF/por_pessoa/acidentes2022.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2023 = pd.read_csv('../PRF/por_pessoa/acidentes2023.csv', sep=';', encoding="ISO-8859-1")
df_pessoa_acidentes_2024 = pd.read_csv('../PRF/por_pessoa/acidentes2024.csv', sep=';', encoding="ISO-8859-1")

/tmp/ipykernel_5179/3339992157.py:4: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2007 = pd.read_csv('../PRF/por_pessoa/acidentes2007.csv', sep=',', encoding="ISO-8859-1")
/tmp/ipykernel_5179/3339992157.py:5: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2008 = pd.read_csv('../PRF/por_pessoa/acidentes2008.csv', sep=',', encoding="ISO-8859-1")
/tmp/ipykernel_5179/3339992157.py:9: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2012 = pd.read_csv('../PRF/por_pessoa/acidentes2012.csv', sep=',', encoding="ISO-8859-1")
/tmp/ipykernel_5179/3339992157.py:14: DtypeWarning: Columns (22,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pessoa_acidentes_2017 = pd.read_csv('../PRF/por_pessoa/acidentes2017.csv', sep=';', encoding="ISO-8859-1")

In [29]:
# =======================================================
# Datasets por ocorrencias
# =======================================================
df_por_ocorrencia_2007 = pd.read_csv('../PRF/por_ocorrencia/datatran2007.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2008 = pd.read_csv('../PRF/por_ocorrencia/datatran2008.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2009 = pd.read_csv('../PRF/por_ocorrencia/datatran2009.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2010 = pd.read_csv('../PRF/por_ocorrencia/datatran2010.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2011 = pd.read_csv('../PRF/por_ocorrencia/datatran2011.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2012 = pd.read_csv('../PRF/por_ocorrencia/datatran2012.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2013 = pd.read_csv('../PRF/por_ocorrencia/datatran2013.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2014 = pd.read_csv('../PRF/por_ocorrencia/datatran2014.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2015 = pd.read_csv('../PRF/por_ocorrencia/datatran2015.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2016 = pd.read_csv('../PRF/por_ocorrencia/datatran2016.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2017 = pd.read_csv('../PRF/por_ocorrencia/datatran2017.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2018 = pd.read_csv('../PRF/por_ocorrencia/datatran2018.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2019 = pd.read_csv('../PRF/por_ocorrencia/datatran2019.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2020 = pd.read_csv('../PRF/por_ocorrencia/datatran2020.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2021 = pd.read_csv('../PRF/por_ocorrencia/datatran2021.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2022 = pd.read_csv('../PRF/por_ocorrencia/datatran2022.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2023 = pd.read_csv('../PRF/por_ocorrencia/datatran2023.csv', sep=';', encoding="ISO-8859-1")
df_por_ocorrencia_2024 = pd.read_csv('../PRF/por_ocorrencia/datatran2024.csv', sep=';', encoding="ISO-8859-1")

/tmp/ipykernel_6166/1112222753.py:4: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_por_ocorrencia_2007 = pd.read_csv('../PRF/por_ocorrencia/datatran2007.csv', sep=';', encoding="ISO-8859-1")
/tmp/ipykernel_6166/1112222753.py:5: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_por_ocorrencia_2008 = pd.read_csv('../PRF/por_ocorrencia/datatran2008.csv', sep=';', encoding="ISO-8859-1")
/tmp/ipykernel_6166/1112222753.py:9: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_por_ocorrencia_2012 = pd.read_csv('../PRF/por_ocorrencia/datatran2012.csv', sep=';', encoding="ISO-8859-1")

In [39]:
# =======================================================
# Funções
# =======================================================
def agrupamento_acidentes_por_ano_por_uf(df):
  contagem_por_uf = df['uf'].value_counts().reset_index()
  contagem_por_uf.columns = ['UF', 'Qtd']
  return contagem_por_uf
# =======================================================
def agrupamento_acidentes_por_ano_por_br(df):
  contagem_por_br = df['br'].value_counts().reset_index()
  contagem_por_br.columns = ['br', 'qtd']
  return contagem_por_br
# =======================================================
def agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes):
  contagem_por_tipo = df_ocorrencia_acidentes['tipo_acidente'].value_counts().reset_index()
  contagem_por_tipo.columns = ['tipo_acidente', 'qtd']
  return contagem_por_tipo
# =======================================================  
def agrupamento_acidentes_por_ano_por_causa(df):
  contagem_por_causa = df['causa_acidente'].value_counts().reset_index()
  contagem_por_causa.columns = ['causa_acidente', 'qtd']
  return contagem_por_causa    
# =======================================================
def agrupamento_acidentes_por_ano_por_classificacao(df):
  contagem_por_classificacao = df['classificacao_acidente'].value_counts().reset_index()
  contagem_por_classificacao.columns = ['classificacao_acidente', 'qtd']
  return contagem_por_classificacao    
# =======================================================
def agrupamento_acidentes_por_ano_por_fase_dia(df):
  contagem_por_fase_dia = df['fase_dia'].value_counts().reset_index(name='qtd')
  contagem_por_fase_dia.columns = ['fase_dia', 'qtd']
  return contagem_por_fase_dia    
# =======================================================
def agrupamento_acidentes_por_ano_por_condicao_metereologica(df):
  contagem_por_condicao_meteorologica = df['condicao_metereologica'].value_counts().reset_index(name='qtd')
  contagem_por_condicao_meteorologica.columns = ['condicao_metereologica', 'qtd']
  return contagem_por_condicao_meteorologica       
# =======================================================
def agrupamento_acidentes_por_ano_por_dia_semana(df):
  contagem_por_dia_semana = df['dia_semana'].value_counts().reset_index(name='qtd')
  contagem_por_dia_semana.columns = ['dia_semana', 'qtd']
  return contagem_por_dia_semana         
# =======================================================
def agrupamento_acidentes_por_ano_por_tipo_veiculo(df):
  contagem_por_tipo_veiculo = df['tipo_veiculo'].value_counts().reset_index(name='qtd')
  contagem_por_tipo_veiculo.columns = ['tipo_veiculo', 'qtd']
  return contagem_por_tipo_veiculo
# =======================================================
def processa_acidentes_geral_tipo_veiculo():
    
    contagem_por_tipo_veiculo_2007 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2007)
    contagem_por_tipo_veiculo_2008 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2008)
    contagem_por_tipo_veiculo_2009 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2009)
    contagem_por_tipo_veiculo_2010 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2010)
    contagem_por_tipo_veiculo_2011 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2011)
    contagem_por_tipo_veiculo_2012 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2012)
    contagem_por_tipo_veiculo_2013 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2013)
    contagem_por_tipo_veiculo_2014 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2014)
    contagem_por_tipo_veiculo_2015 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2015)
    contagem_por_tipo_veiculo_2016 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2016)
    contagem_por_tipo_veiculo_2017 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2017)
    contagem_por_tipo_veiculo_2018 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2018)
    contagem_por_tipo_veiculo_2019 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2019)
    contagem_por_tipo_veiculo_2020 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2020)
    contagem_por_tipo_veiculo_2021 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2021)
    contagem_por_tipo_veiculo_2022 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2022)
    contagem_por_tipo_veiculo_2023 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2023)
    contagem_por_tipo_veiculo_2024 = agrupamento_acidentes_por_ano_por_tipo_veiculo(df_pessoa_acidentes_2024)
    
    contagem_por_tipo_veiculo_2007['ano'] = '2007'
    contagem_por_tipo_veiculo_2008['ano'] = '2008'
    contagem_por_tipo_veiculo_2009['ano'] = '2009'
    contagem_por_tipo_veiculo_2010['ano'] = '2010'
    contagem_por_tipo_veiculo_2011['ano'] = '2011'
    contagem_por_tipo_veiculo_2012['ano'] = '2012'
    contagem_por_tipo_veiculo_2013['ano'] = '2013'
    contagem_por_tipo_veiculo_2014['ano'] = '2014'
    contagem_por_tipo_veiculo_2015['ano'] = '2015'
    contagem_por_tipo_veiculo_2016['ano'] = '2016'
    contagem_por_tipo_veiculo_2017['ano'] = '2017'
    contagem_por_tipo_veiculo_2018['ano'] = '2018'
    contagem_por_tipo_veiculo_2019['ano'] = '2019'
    contagem_por_tipo_veiculo_2020['ano'] = '2020'
    contagem_por_tipo_veiculo_2021['ano'] = '2021'
    contagem_por_tipo_veiculo_2022['ano'] = '2022'
    contagem_por_tipo_veiculo_2023['ano'] = '2023'
    contagem_por_tipo_veiculo_2024['ano'] = '2024'

    acidentes_por_tipo_veiculo_concatenados = pd.concat(
    [
      contagem_por_tipo_veiculo_2007, contagem_por_tipo_veiculo_2008, contagem_por_tipo_veiculo_2009,
      contagem_por_tipo_veiculo_2010, contagem_por_tipo_veiculo_2011, contagem_por_tipo_veiculo_2012,
      contagem_por_tipo_veiculo_2013, contagem_por_tipo_veiculo_2014, contagem_por_tipo_veiculo_2015,
      contagem_por_tipo_veiculo_2016, contagem_por_tipo_veiculo_2017, contagem_por_tipo_veiculo_2018,
      contagem_por_tipo_veiculo_2019, contagem_por_tipo_veiculo_2020, contagem_por_tipo_veiculo_2021,
      contagem_por_tipo_veiculo_2022, contagem_por_tipo_veiculo_2023, contagem_por_tipo_veiculo_2024
    
    ], axis=0)
    
    lista_tipos_veiculos = []
    
    for item in acidentes_por_tipo_veiculo_concatenados['tipo_veiculo'].unique():
      lista_tipos_veiculos.append(item)
    lista_tipos_veiculos.remove('(null)')
    
    lista_tipos_veiculos = lista_tipos_veiculos[:10]
    df_tipo_veiculo = acidentes_por_tipo_veiculo_concatenados
    df_geral_tipo_veiculo = pd.DataFrame(columns=['tipo_veiculo','qtd','ano'])
    
    for item in lista_tipos_veiculos:
      df_filtrado_uf = df_tipo_veiculo[(df_tipo_veiculo['tipo_veiculo'] == item)]
      df_geral_tipo_veiculo = pd.concat([df_geral_tipo_veiculo, df_filtrado_uf], ignore_index=True)
        
    df_geral_tipo_veiculo.to_csv('acidentes_geral_por_tipo_veiculo.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_tipo_veiculo...')

    return df_geral_tipo_veiculo
# =======================================================
def processa_acidentes_geral_ufs():
    
    contagem_por_uf_2007 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2007)
    contagem_por_uf_2008 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2008)
    contagem_por_uf_2009 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2009)
    contagem_por_uf_2010 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2010)
    contagem_por_uf_2011 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2011)
    contagem_por_uf_2012 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2012)
    contagem_por_uf_2013 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2013)
    contagem_por_uf_2014 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2014)
    contagem_por_uf_2015 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2015)
    contagem_por_uf_2016 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2016)
    contagem_por_uf_2017 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2017)
    contagem_por_uf_2018 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2018)
    contagem_por_uf_2019 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2019)
    contagem_por_uf_2020 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2020)
    contagem_por_uf_2021 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2021)
    contagem_por_uf_2022 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2022)
    contagem_por_uf_2023 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2023)
    contagem_por_uf_2024 = agrupamento_acidentes_por_ano_por_uf(df_pessoa_acidentes_2024)
    
    contagem_por_uf_2007['ano'] = '2007'
    contagem_por_uf_2008['ano'] = '2008'
    contagem_por_uf_2009['ano'] = '2009'
    contagem_por_uf_2010['ano'] = '2010'
    contagem_por_uf_2011['ano'] = '2011'
    contagem_por_uf_2012['ano'] = '2012'
    contagem_por_uf_2013['ano'] = '2013'
    contagem_por_uf_2014['ano'] = '2014'
    contagem_por_uf_2015['ano'] = '2015'
    contagem_por_uf_2016['ano'] = '2016'
    contagem_por_uf_2017['ano'] = '2017'
    contagem_por_uf_2018['ano'] = '2018'
    contagem_por_uf_2019['ano'] = '2019'
    contagem_por_uf_2020['ano'] = '2020'
    contagem_por_uf_2021['ano'] = '2021'
    contagem_por_uf_2022['ano'] = '2022'
    contagem_por_uf_2023['ano'] = '2023'
    contagem_por_uf_2024['ano'] = '2024'

    acidentes_por_uf_concatenados = pd.concat(
    [
      contagem_por_uf_2007, contagem_por_uf_2008, contagem_por_uf_2009,
      contagem_por_uf_2010, contagem_por_uf_2011, contagem_por_uf_2012,
      contagem_por_uf_2013, contagem_por_uf_2014, contagem_por_uf_2015,
      contagem_por_uf_2016, contagem_por_uf_2017, contagem_por_uf_2018,
      contagem_por_uf_2019, contagem_por_uf_2020, contagem_por_uf_2021,
      contagem_por_uf_2022, contagem_por_uf_2023, contagem_por_uf_2024
    
    ], axis=0)
    
    lista_ufs = []
    
    for item in acidentes_por_uf_concatenados['UF'].unique():
      lista_ufs.append(item)
    lista_ufs.remove('(null)')
    
    lista_ufs = lista_ufs[:10]
    df_uf = acidentes_por_uf_concatenados
    df_geral_uf = pd.DataFrame(columns=['UF','Qtd','ano'])
    
    for item in lista_ufs:
      df_filtrado_uf = df_uf[(df_uf['UF'] == item)]
      df_geral_uf = pd.concat([df_geral_uf, df_filtrado_uf], ignore_index=True)
        
    df_geral_uf.to_csv('acidentes_geral_por_uf.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_uf...')

    return df_geral_uf
# =======================================================
def processa_acidentes_geral_tipo():

    df_ocorrencia_acidentes_2007 = pd.read_csv('../PRF/por_ocorrencia/datatran2007.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2008 = pd.read_csv('../PRF/por_ocorrencia/datatran2008.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2009 = pd.read_csv('../PRF/por_ocorrencia/datatran2009.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2010 = pd.read_csv('../PRF/por_ocorrencia/datatran2010.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2011 = pd.read_csv('../PRF/por_ocorrencia/datatran2011.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2012 = pd.read_csv('../PRF/por_ocorrencia/datatran2012.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2013 = pd.read_csv('../PRF/por_ocorrencia/datatran2013.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2014 = pd.read_csv('../PRF/por_ocorrencia/datatran2014.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2015 = pd.read_csv('../PRF/por_ocorrencia/datatran2015.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2016 = pd.read_csv('../PRF/por_ocorrencia/datatran2016.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2017 = pd.read_csv('../PRF/por_ocorrencia/datatran2017.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2018 = pd.read_csv('../PRF/por_ocorrencia/datatran2018.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2019 = pd.read_csv('../PRF/por_ocorrencia/datatran2019.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2020 = pd.read_csv('../PRF/por_ocorrencia/datatran2020.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2021 = pd.read_csv('../PRF/por_ocorrencia/datatran2021.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2022 = pd.read_csv('../PRF/por_ocorrencia/datatran2022.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2023 = pd.read_csv('../PRF/por_ocorrencia/datatran2023.csv', sep=';', encoding="ISO-8859-1", low_memory=False)
    df_ocorrencia_acidentes_2024 = pd.read_csv('../PRF/por_ocorrencia/datatran2024.csv', sep=';', encoding="ISO-8859-1", low_memory=False)

    contagem_por_tipo_2007 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2007)
    contagem_por_tipo_2008 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2008)
    contagem_por_tipo_2009 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2009)
    contagem_por_tipo_2010 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2010)
    contagem_por_tipo_2011 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2011)
    contagem_por_tipo_2012 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2012)
    contagem_por_tipo_2013 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2013)
    contagem_por_tipo_2014 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2014)
    contagem_por_tipo_2015 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2015)
    contagem_por_tipo_2016 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2016)
    contagem_por_tipo_2017 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2017)
    contagem_por_tipo_2018 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2018)
    contagem_por_tipo_2019 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2019)
    contagem_por_tipo_2020 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2020)
    contagem_por_tipo_2021 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2021)
    contagem_por_tipo_2022 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2022)
    contagem_por_tipo_2023 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2023)
    contagem_por_tipo_2024 = agrupamento_acidentes_por_ano_por_tipo(df_ocorrencia_acidentes_2024)
    
    contagem_por_tipo_2007['ano'] = '2007'
    contagem_por_tipo_2008['ano'] = '2008'
    contagem_por_tipo_2009['ano'] = '2009'
    contagem_por_tipo_2010['ano'] = '2010'
    contagem_por_tipo_2011['ano'] = '2011'
    contagem_por_tipo_2012['ano'] = '2012'
    contagem_por_tipo_2013['ano'] = '2013'
    contagem_por_tipo_2014['ano'] = '2014'
    contagem_por_tipo_2015['ano'] = '2015'
    contagem_por_tipo_2016['ano'] = '2016'
    contagem_por_tipo_2017['ano'] = '2017'
    contagem_por_tipo_2018['ano'] = '2018'
    contagem_por_tipo_2019['ano'] = '2019'
    contagem_por_tipo_2020['ano'] = '2020'
    contagem_por_tipo_2021['ano'] = '2021'
    contagem_por_tipo_2022['ano'] = '2022'
    contagem_por_tipo_2023['ano'] = '2023'
    contagem_por_tipo_2024['ano'] = '2024'
    
    
    acidentes_por_tipo_concatenados = pd.concat(
    [
        contagem_por_tipo_2007, contagem_por_tipo_2008, contagem_por_tipo_2009,
        contagem_por_tipo_2010, contagem_por_tipo_2011, contagem_por_tipo_2012,
        contagem_por_tipo_2013, contagem_por_tipo_2014, contagem_por_tipo_2015,
        contagem_por_tipo_2016, contagem_por_tipo_2017, contagem_por_tipo_2018,
        contagem_por_tipo_2019, contagem_por_tipo_2020, contagem_por_tipo_2021,
        contagem_por_tipo_2022, contagem_por_tipo_2023, contagem_por_tipo_2024
    
    ], axis=0)
    
    acidentes_por_tipo_concatenados
    
    df_tipo = acidentes_por_tipo_concatenados
    df_geral_tipo = pd.DataFrame(columns=['tipo_acidente','qtd','ano'])

    lista_acidentes = contagem_por_tipo_2023['tipo_acidente'].unique()
    lista_acidentes = lista_acidentes[:15]
    lista_acidentes
    
    for item in lista_acidentes:
      df_filtrado_tipo = df_tipo[(df_tipo['tipo_acidente'] == item)]
      df_geral_tipo = pd.concat([df_geral_tipo, df_filtrado_tipo], ignore_index=True)
    
    df_geral_tipo
    
    df_geral_tipo.to_csv('acidentes_geral_por_tipo.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_tipo.csv...')
    
    return df_geral_tipo
# =======================================================
def processa_acidentes_geral_br():

    acidentes_br_2007 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2007)
    acidentes_br_2008 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2008)
    acidentes_br_2009 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2009)
    acidentes_br_2010 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2010)
    acidentes_br_2011 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2011)
    acidentes_br_2012 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2012)
    acidentes_br_2013 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2013)
    acidentes_br_2014 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2014)
    acidentes_br_2015 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2015)
    acidentes_br_2016 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2016)
    acidentes_br_2017 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2017)
    acidentes_br_2018 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2018)
    acidentes_br_2019 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2019)
    acidentes_br_2020 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2020)
    acidentes_br_2021 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2021)
    acidentes_br_2022 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2022)
    acidentes_br_2023 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2023)
    acidentes_br_2024 = agrupamento_acidentes_por_ano_por_br(df_pessoa_acidentes_2024)   
   
    acidentes_br_2007['ano'] = '2007'
    acidentes_br_2008['ano'] = '2008'
    acidentes_br_2009['ano'] = '2009'
    acidentes_br_2010['ano'] = '2010'
    acidentes_br_2011['ano'] = '2011'
    acidentes_br_2012['ano'] = '2012'
    acidentes_br_2013['ano'] = '2013'
    acidentes_br_2014['ano'] = '2014'
    acidentes_br_2015['ano'] = '2015'
    acidentes_br_2016['ano'] = '2016'
    acidentes_br_2017['ano'] = '2017'
    acidentes_br_2018['ano'] = '2018'
    acidentes_br_2019['ano'] = '2019'
    acidentes_br_2020['ano'] = '2020'
    acidentes_br_2021['ano'] = '2021'
    acidentes_br_2022['ano'] = '2022'
    acidentes_br_2023['ano'] = '2023'
    acidentes_br_2024['ano'] = '2024'
    
    acidentes_brs_concatenados = pd.concat(
    [
        acidentes_br_2007, acidentes_br_2008, acidentes_br_2009,
        acidentes_br_2010, acidentes_br_2011, acidentes_br_2012,
        acidentes_br_2013, acidentes_br_2014, acidentes_br_2015,
        acidentes_br_2016, acidentes_br_2017, acidentes_br_2018,
        acidentes_br_2019, acidentes_br_2020, acidentes_br_2021,
        acidentes_br_2022, acidentes_br_2023, acidentes_br_2024
    ], axis=0)
    
    acidentes_brs_concatenados
    
    lista_brs = ['101','116','381','40','153','163','364','227','376','262','230','470','316','282','70','60','20','158','369','50']
    
    df = acidentes_brs_concatenados
    df_geral_br = pd.DataFrame(columns=['br', 'qtd', 'ano'])
    
    for item in lista_brs:
      df_filtrado_br = df[(df['br'] == int(item))]
      df_geral_br = pd.concat([df_geral_br, df_filtrado_br], ignore_index=True)

    df_geral_br
    df_geral_br.to_csv('acidentes_geral_por_br.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_br.csv...')
    
    return df_geral_br   
# =======================================================
def processa_acidentes_geral_causa():
    
    contagem_por_causa_2007 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2007)
    contagem_por_causa_2008 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2008)
    contagem_por_causa_2009 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2009)
    contagem_por_causa_2010 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2010)
    contagem_por_causa_2011 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2011)
    contagem_por_causa_2012 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2012)
    contagem_por_causa_2013 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2013)
    contagem_por_causa_2014 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2014)
    contagem_por_causa_2015 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2015)
    contagem_por_causa_2016 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2016)
    contagem_por_causa_2017 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2017)
    contagem_por_causa_2018 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2018)
    contagem_por_causa_2019 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2019)
    contagem_por_causa_2020 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2020)
    contagem_por_causa_2021 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2021)
    contagem_por_causa_2022 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2022)
    contagem_por_causa_2023 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2023)
    contagem_por_causa_2024 = agrupamento_acidentes_por_ano_por_causa(df_pessoa_acidentes_2024)
    
    contagem_por_causa_2007['ano'] = '2007'
    contagem_por_causa_2008['ano'] = '2008'
    contagem_por_causa_2009['ano'] = '2009'
    contagem_por_causa_2010['ano'] = '2010'
    contagem_por_causa_2011['ano'] = '2011'
    contagem_por_causa_2012['ano'] = '2012'
    contagem_por_causa_2013['ano'] = '2013'
    contagem_por_causa_2014['ano'] = '2014'
    contagem_por_causa_2015['ano'] = '2015'
    contagem_por_causa_2016['ano'] = '2016'
    contagem_por_causa_2017['ano'] = '2017'
    contagem_por_causa_2018['ano'] = '2018'
    contagem_por_causa_2019['ano'] = '2019'
    contagem_por_causa_2020['ano'] = '2020'
    contagem_por_causa_2021['ano'] = '2021'
    contagem_por_causa_2022['ano'] = '2022'
    contagem_por_causa_2023['ano'] = '2023'
    contagem_por_causa_2024['ano'] = '2024'

    acidentes_por_causa_concatenados = pd.concat(
    [
      contagem_por_causa_2007, contagem_por_causa_2008, contagem_por_causa_2009,
      contagem_por_causa_2010, contagem_por_causa_2011, contagem_por_causa_2012,
      contagem_por_causa_2013, contagem_por_causa_2014, contagem_por_causa_2015,
      contagem_por_causa_2016, contagem_por_causa_2017, contagem_por_causa_2018,
      contagem_por_causa_2019, contagem_por_causa_2020, contagem_por_causa_2021,
      contagem_por_causa_2022, contagem_por_causa_2023, contagem_por_causa_2024
    
    ], axis=0)
    
    lista_causas = []
    
    for item in acidentes_por_causa_concatenados['causa_acidente'].unique():
      lista_causas.append(item)
    lista_causas.remove('(null)')
    
    lista_causas = lista_causas[:25]
    
    df_causa = acidentes_por_causa_concatenados
    df_geral_causa = pd.DataFrame(columns=['causa_acidente','qtd','ano'])
    
    for item in lista_causas:
      df_filtrado_causa = df_causa[(df_causa['causa_acidente'] == item)]
      df_geral_causa = pd.concat([df_geral_causa, df_filtrado_causa], ignore_index=True)
        
    df_geral_causa.to_csv('acidentes_geral_por_causa.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_causa.csv...')

    return df_geral_causa
# =======================================================
def processa_acidentes_geral_classificacao():
    
    contagem_por_classificacao_2007 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2007)
    contagem_por_classificacao_2008 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2008)
    contagem_por_classificacao_2009 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2009)
    contagem_por_classificacao_2010 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2010)
    contagem_por_classificacao_2011 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2011)
    contagem_por_classificacao_2012 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2012)
    contagem_por_classificacao_2013 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2013)
    contagem_por_classificacao_2014 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2014)
    contagem_por_classificacao_2015 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2015)
    contagem_por_classificacao_2016 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2016)
    contagem_por_classificacao_2017 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2017)
    contagem_por_classificacao_2018 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2018)
    contagem_por_classificacao_2019 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2019)
    contagem_por_classificacao_2020 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2020)
    contagem_por_classificacao_2021 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2021)
    contagem_por_classificacao_2022 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2022)
    contagem_por_classificacao_2023 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2023)
    contagem_por_classificacao_2024 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2024)
    
    contagem_por_classificacao_2007['ano'] = '2007'
    contagem_por_classificacao_2008['ano'] = '2008'
    contagem_por_classificacao_2009['ano'] = '2009'
    contagem_por_classificacao_2010['ano'] = '2010'
    contagem_por_classificacao_2011['ano'] = '2011'
    contagem_por_classificacao_2012['ano'] = '2012'
    contagem_por_classificacao_2013['ano'] = '2013'
    contagem_por_classificacao_2014['ano'] = '2014'
    contagem_por_classificacao_2015['ano'] = '2015'
    contagem_por_classificacao_2016['ano'] = '2016'
    contagem_por_classificacao_2017['ano'] = '2017'
    contagem_por_classificacao_2018['ano'] = '2018'
    contagem_por_classificacao_2019['ano'] = '2019'
    contagem_por_classificacao_2020['ano'] = '2020'
    contagem_por_classificacao_2021['ano'] = '2021'
    contagem_por_classificacao_2022['ano'] = '2022'
    contagem_por_classificacao_2023['ano'] = '2023'
    contagem_por_classificacao_2024['ano'] = '2024'

    acidentes_por_classificacao_concatenados = pd.concat(
    [
      contagem_por_classificacao_2007, contagem_por_classificacao_2008, contagem_por_classificacao_2009,
      contagem_por_classificacao_2010, contagem_por_classificacao_2011, contagem_por_classificacao_2012,
      contagem_por_classificacao_2013, contagem_por_classificacao_2014, contagem_por_classificacao_2015,
      contagem_por_classificacao_2016, contagem_por_classificacao_2017, contagem_por_classificacao_2018,
      contagem_por_classificacao_2019, contagem_por_classificacao_2020, contagem_por_classificacao_2021,
      contagem_por_classificacao_2022, contagem_por_classificacao_2023, contagem_por_classificacao_2024
    
    ], axis=0)
    
    lista_classificacoes_antes = acidentes_por_classificacao_concatenados['classificacao_acidente'].unique()
    print(f'lista_classificacoes_antes => {lista_classificacoes_antes}')
    
    lista_classificacoes_depois = [item.rstrip() for item in lista_classificacoes_antes]
    lista_classificacoes_depois.remove('(null)')
    
    print(f'lista_classificacoes_depois => {lista_classificacoes_depois}')
    
    lista_sem_duplicacacoes = list(set(lista_classificacoes_depois))
    print(f'lista_sem_duplicacacoes => {lista_sem_duplicacacoes}')
    
    
    lista_classificacoes = lista_sem_duplicacacoes
    
    print(f'lista_classificacoes => {lista_classificacoes} ')
    
    df_classificacao = acidentes_por_classificacao_concatenados
    df_geral_classificacao = pd.DataFrame(columns=['classificacao_acidente','qtd','ano'])
    
    for item in lista_classificacoes:
      df_filtrado_classificacao = df_classificacao[(df_classificacao['classificacao_acidente'] == item)]
      df_geral_classificacao = pd.concat([df_geral_classificacao, df_filtrado_classificacao], ignore_index=True)
    
    df_geral_classificacao.to_csv('acidentes_geral_por_classificacao.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_classificacao.csv...')
    
    return df_geral_classificacao   
# =======================================================
def processa_acidentes_geral_fase_dia():
    
    contagem_por_fase_dia_2007 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2007)
    contagem_por_fase_dia_2008 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2008)
    contagem_por_fase_dia_2009 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2009)
    contagem_por_fase_dia_2010 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2010)
    contagem_por_fase_dia_2011 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2011)
    contagem_por_fase_dia_2012 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2012)
    contagem_por_fase_dia_2013 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2013)
    contagem_por_fase_dia_2014 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2014)
    contagem_por_fase_dia_2015 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2015)
    contagem_por_fase_dia_2016 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2016)
    contagem_por_fase_dia_2017 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2017)
    contagem_por_fase_dia_2018 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2018)
    contagem_por_fase_dia_2019 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2019)
    contagem_por_fase_dia_2020 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2020)
    contagem_por_fase_dia_2021 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2021)
    contagem_por_fase_dia_2022 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2022)
    contagem_por_fase_dia_2023 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2023)
    contagem_por_fase_dia_2024 = agrupamento_acidentes_por_ano_por_fase_dia(df_pessoa_acidentes_2024)
    
    contagem_por_fase_dia_2007['ano'] = '2007'
    contagem_por_fase_dia_2008['ano'] = '2008'
    contagem_por_fase_dia_2009['ano'] = '2009'
    contagem_por_fase_dia_2010['ano'] = '2010'
    contagem_por_fase_dia_2011['ano'] = '2011'
    contagem_por_fase_dia_2012['ano'] = '2012'
    contagem_por_fase_dia_2013['ano'] = '2013'
    contagem_por_fase_dia_2014['ano'] = '2014'
    contagem_por_fase_dia_2015['ano'] = '2015'
    contagem_por_fase_dia_2016['ano'] = '2016'
    contagem_por_fase_dia_2017['ano'] = '2017'
    contagem_por_fase_dia_2018['ano'] = '2018'
    contagem_por_fase_dia_2019['ano'] = '2019'
    contagem_por_fase_dia_2020['ano'] = '2020'
    contagem_por_fase_dia_2021['ano'] = '2021'
    contagem_por_fase_dia_2022['ano'] = '2022'
    contagem_por_fase_dia_2023['ano'] = '2023'
    contagem_por_fase_dia_2024['ano'] = '2024'

    acidentes_por_fase_dia_concatenados = pd.concat(
    [
      contagem_por_fase_dia_2007, contagem_por_fase_dia_2008, contagem_por_fase_dia_2009,
      contagem_por_fase_dia_2010, contagem_por_fase_dia_2011, contagem_por_fase_dia_2012,
      contagem_por_fase_dia_2013, contagem_por_fase_dia_2014, contagem_por_fase_dia_2015,
      contagem_por_fase_dia_2016, contagem_por_fase_dia_2017, contagem_por_fase_dia_2018,
      contagem_por_fase_dia_2019, contagem_por_fase_dia_2020, contagem_por_fase_dia_2021,
      contagem_por_fase_dia_2022, contagem_por_fase_dia_2023, contagem_por_fase_dia_2024
    
    ], axis=0)
    
    lista_fases = []
    
    for item in acidentes_por_fase_dia_concatenados['fase_dia'].unique():
      lista_fases.append(item)
    lista_fases.remove('(null)')
        
    df_fase = acidentes_por_fase_dia_concatenados
    df_geral_fase_dia = pd.DataFrame(columns=['fase_dia','qtd','ano'])
    
    for item in lista_fases:
      df_filtrado_fase = df_fase[(df_fase['fase_dia'] == item)]
      df_geral_fase_dia = pd.concat([df_geral_fase_dia, df_filtrado_fase], ignore_index=True)
        
    df_geral_fase_dia.to_csv('acidentes_geral_por_fase_dia.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_fase_dia.csv...')

    return df_geral_fase_dia  
# =======================================================
def processa_acidentes_geral_condicao_metereologica():

    contagem_por_condicao_metereologica_2007 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2007)
    contagem_por_condicao_metereologica_2008 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2008)
    contagem_por_condicao_metereologica_2009 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2009)
    contagem_por_condicao_metereologica_2010 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2010)
    contagem_por_condicao_metereologica_2011 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2011)
    contagem_por_condicao_metereologica_2012 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2012)
    contagem_por_condicao_metereologica_2013 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2013)
    contagem_por_condicao_metereologica_2014 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2014)
    contagem_por_condicao_metereologica_2015 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2015)
    contagem_por_condicao_metereologica_2016 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2016)
    contagem_por_condicao_metereologica_2017 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2017)
    contagem_por_condicao_metereologica_2018 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2018)
    contagem_por_condicao_metereologica_2019 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2019)
    contagem_por_condicao_metereologica_2020 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2020)
    contagem_por_condicao_metereologica_2021 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2021)
    contagem_por_condicao_metereologica_2022 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2022)
    contagem_por_condicao_metereologica_2023 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2023)
    contagem_por_condicao_metereologica_2024 = agrupamento_acidentes_por_ano_por_condicao_metereologica(df_pessoa_acidentes_2024)
    
    contagem_por_condicao_metereologica_2007['ano'] = '2007'
    contagem_por_condicao_metereologica_2008['ano'] = '2008'
    contagem_por_condicao_metereologica_2009['ano'] = '2009'
    contagem_por_condicao_metereologica_2010['ano'] = '2010'
    contagem_por_condicao_metereologica_2011['ano'] = '2011'
    contagem_por_condicao_metereologica_2012['ano'] = '2012'
    contagem_por_condicao_metereologica_2013['ano'] = '2013'
    contagem_por_condicao_metereologica_2014['ano'] = '2014'
    contagem_por_condicao_metereologica_2015['ano'] = '2015'
    contagem_por_condicao_metereologica_2016['ano'] = '2016'
    contagem_por_condicao_metereologica_2017['ano'] = '2017'
    contagem_por_condicao_metereologica_2018['ano'] = '2018'
    contagem_por_condicao_metereologica_2019['ano'] = '2019'
    contagem_por_condicao_metereologica_2020['ano'] = '2020'
    contagem_por_condicao_metereologica_2021['ano'] = '2021'
    contagem_por_condicao_metereologica_2022['ano'] = '2022'
    contagem_por_condicao_metereologica_2023['ano'] = '2023'
    contagem_por_condicao_metereologica_2024['ano'] = '2024'

    acidentes_por_condicao_metereologica_concatenados = pd.concat(
    [
      contagem_por_condicao_metereologica_2007, contagem_por_condicao_metereologica_2008, contagem_por_condicao_metereologica_2009,
      contagem_por_condicao_metereologica_2010, contagem_por_condicao_metereologica_2011, contagem_por_condicao_metereologica_2012,
      contagem_por_condicao_metereologica_2013, contagem_por_condicao_metereologica_2014, contagem_por_condicao_metereologica_2015,
      contagem_por_condicao_metereologica_2016, contagem_por_condicao_metereologica_2017, contagem_por_condicao_metereologica_2018,
      contagem_por_condicao_metereologica_2019, contagem_por_condicao_metereologica_2020, contagem_por_condicao_metereologica_2021,
      contagem_por_condicao_metereologica_2022, contagem_por_condicao_metereologica_2023, contagem_por_condicao_metereologica_2024
    
    ], axis=0)
    
    lista_condicoes = []
    
    for item in acidentes_por_condicao_metereologica_concatenados['condicao_metereologica'].unique():
      lista_condicoes.append(item)
   
    df_condicao = acidentes_por_condicao_metereologica_concatenados
    df_geral_condicao_metereologica = pd.DataFrame(columns=['condicao_metereologica','qtd','ano'])
    
    for item in lista_condicoes:
      df_filtrado_classificacao = df_condicao[(df_condicao['condicao_metereologica'] == item)]
      df_geral_condicao_metereologica = pd.concat([df_geral_condicao_metereologica, df_filtrado_classificacao], ignore_index=True)
        
    df_geral_condicao_metereologica.to_csv('acidentes_geral_por_condicao_metereologica.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_condicao_metereologica.csv...')

    return df_geral_condicao_metereologica   
# =======================================================   
def processa_acidentes_geral_dia_semana():
    
    contagem_por_dia_semana_2007 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2007)
    contagem_por_dia_semana_2008 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2008)
    contagem_por_dia_semana_2009 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2009)
    contagem_por_dia_semana_2010 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2010)
    contagem_por_dia_semana_2011 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2011)
    contagem_por_dia_semana_2012 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2012)
    contagem_por_dia_semana_2013 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2013)
    contagem_por_dia_semana_2014 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2014)
    contagem_por_dia_semana_2015 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2015)
    contagem_por_dia_semana_2016 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2016)
    contagem_por_dia_semana_2017 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2017)
    contagem_por_dia_semana_2018 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2018)
    contagem_por_dia_semana_2019 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2019)
    contagem_por_dia_semana_2020 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2020)
    contagem_por_dia_semana_2021 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2021)
    contagem_por_dia_semana_2022 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2022)
    contagem_por_dia_semana_2023 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2023)
    contagem_por_dia_semana_2024 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2024)
    
    contagem_por_dia_semana_2007['ano'] = '2007'
    contagem_por_dia_semana_2008['ano'] = '2008'
    contagem_por_dia_semana_2009['ano'] = '2009'
    contagem_por_dia_semana_2010['ano'] = '2010'
    contagem_por_dia_semana_2011['ano'] = '2011'
    contagem_por_dia_semana_2012['ano'] = '2012'
    contagem_por_dia_semana_2013['ano'] = '2013'
    contagem_por_dia_semana_2014['ano'] = '2014'
    contagem_por_dia_semana_2015['ano'] = '2015'
    contagem_por_dia_semana_2016['ano'] = '2016'
    contagem_por_dia_semana_2017['ano'] = '2017'
    contagem_por_dia_semana_2018['ano'] = '2018'
    contagem_por_dia_semana_2019['ano'] = '2019'
    contagem_por_dia_semana_2020['ano'] = '2020'
    contagem_por_dia_semana_2021['ano'] = '2021'
    contagem_por_dia_semana_2022['ano'] = '2022'
    contagem_por_dia_semana_2023['ano'] = '2023'
    contagem_por_dia_semana_2024['ano'] = '2024'

    acidentes_por_dia_semana_concatenados = pd.concat(
    [
      contagem_por_dia_semana_2007, contagem_por_dia_semana_2008, contagem_por_dia_semana_2009,
      contagem_por_dia_semana_2010, contagem_por_dia_semana_2011, contagem_por_dia_semana_2012,
      contagem_por_dia_semana_2013, contagem_por_dia_semana_2014, contagem_por_dia_semana_2015,
      contagem_por_dia_semana_2016, contagem_por_dia_semana_2017, contagem_por_dia_semana_2018,
      contagem_por_dia_semana_2019, contagem_por_dia_semana_2020, contagem_por_dia_semana_2021,
      contagem_por_dia_semana_2022, contagem_por_dia_semana_2023, contagem_por_dia_semana_2024
    
    ], axis=0)
    
    lista_dias_semanas = ['dom','seg','ter','qua','qui','sex','sáb']
    
    print(f'\n\n lista_dias_semanas ({len(lista_dias_semanas)}) => {lista_dias_semanas}...')
    
    df_dias_semana = acidentes_por_dia_semana_concatenados
    df_dias_semana['dia_semana'] = df_dias_semana['dia_semana'].str.lower()
    print(f'\n df_geral_dias_semanas => {df_dias_semana}')

    df_geral_dias_semanas = pd.DataFrame(columns=['dia_semana','qtd','ano'])

    for item in lista_dias_semanas:
      df_filtrado_dias_semana = df_dias_semana[(df_dias_semana['dia_semana'].str.find(item.lower()) != -1)]
      df_geral_dias_semanas = pd.concat([df_geral_dias_semanas, df_filtrado_dias_semana], ignore_index=True)
    
    df_geral_dias_semanas.to_csv('acidentes_geral_por_dia_semana.csv', index=False)
    print('\n\nSalvando arquivo acidentes_geral_por_dia_semana...')

    return df_geral_dias_semanas
# =======================================================      
def ajusta_dia_semana(value):
    if value == 'domingo' or value == 'Domingo':
        return 'Domingo'
        
    elif value == 'segunda' or value == 'segunda-feira':    
        return 'Segunda-feira'
        
    elif value == 'terça' or value == 'terça-feira':    
        return 'Terça-feira'
        
    elif value == 'quarta' or value == 'quarta-feira':    
        return 'Quarta-feira'
        
    elif value == 'quinta' or value == 'quinta-feira':    
        return 'Quinta-feira'
        
    elif value == 'sexta' or value == 'sexta-feira':    
        return 'Sexta-feira'
        
    elif value == 'sábado' or value == 'Sábado':    
        return 'Sábado'    

    return value
# =======================================================   
def gera_grafico_por_uf(titulo, contagem_por_uf_ano):

  lista_cores = alt.Scale(domain= contagem_por_uf_ano['UF'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart_uf = alt.Chart(contagem_por_uf_ano).mark_bar().encode(
      y=alt.Y('UF:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('Qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['UF', 'Qtd'],
      color=alt.Color('UF:N', scale=lista_cores)

  ).properties(
      title=alt.Title(
        text=titulo  
      ),
      width=800
  ).interactive()

  return chart_uf
# =======================================================
def gera_grafico_por_tipo(titulo, contagem_por_tipo_ano):

  lista_cores = alt.Scale(domain=contagem_por_tipo_ano['tipo_acidente'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart_tipo = alt.Chart(contagem_por_tipo_ano).mark_bar().encode(
      y=alt.Y('tipo_acidente:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['tipo_acidente', 'qtd'],
      color=alt.Color('tipo_acidente:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600           
  ).interactive()

  return chart_tipo
# =======================================================
def gera_grafico_barras_horizontal_por_br(titulo, contagem_por_br_ano):

  lista_cores = alt.Scale(domain=contagem_por_br_ano['br'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart_br = alt.Chart(contagem_por_br_ano).mark_bar().encode(
      y=alt.Y('br:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['br', 'qtd'],
      color=alt.Color('br:N', scale=lista_cores)

  ).properties(
      title=titulo
  ).interactive()

  return chart_br
# =======================================================
def gera_grafico_por_causa(titulo, contagem_por_causa_ano):

  lista_cores = alt.Scale(domain=contagem_por_causa_ano['causa_acidente'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_causa_ano).mark_bar().encode(
      y=alt.Y('causa_acidente:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['causa_acidente', 'qtd'],
      color=alt.Color('causa_acidente:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart

# =======================================================
def gera_grafico_por_classificacao(titulo, contagem_por_classificacao_ano):

  lista_cores = alt.Scale(domain=contagem_por_classificacao_ano['classificacao_acidente'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_classificacao_ano).mark_bar().encode(
      y=alt.Y('classificacao_acidente:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['classificacao_acidente', 'qtd'],
      color=alt.Color('classificacao_acidente:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart
# =======================================================
def gera_grafico_por_fase_dia(titulo, contagem_por_fase_dia):

  lista_cores = alt.Scale(domain=contagem_por_fase_dia['fase_dia'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_fase_dia).mark_bar().encode(
      y=alt.Y('fase_dia:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['fase_dia', 'qtd'],
      color=alt.Color('fase_dia:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart
# =======================================================
def gera_grafico_por_condicao_metereologica(titulo, contagem_por_condicao_metereologica):

  lista_cores = alt.Scale(domain=contagem_por_condicao_metereologica['condicao_metereologica'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_condicao_metereologica).mark_bar().encode(
      y=alt.Y('condicao_metereologica:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['condicao_metereologica', 'qtd'],
      color=alt.Color('condicao_metereologica:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart
# =======================================================
def gera_grafico_por_dia_semana(titulo, contagem_por_dia_semana):

  lista_cores = alt.Scale(domain=contagem_por_dia_semana['dia_semana'].unique(),
      range=[
        '#007bff', '#28a745', '#ffc107', '#dc3545', '#6c757d', '#d95b43', '#5bc0de', '#4caf50', '#ffeb3b', '#c497d9',
        '#00BFFF', '#32CD32', '#FF00FF', '#FFA500', '#5A87E8', '#00CED1', '#FF7F50', '#228B22', '#FFD700', '#000080',
        '#FF1493', '#4B0082', '#8A2BE2', '#7FFF00', '#00FFFF', '#008000'
      ])

  chart = alt.Chart(contagem_por_dia_semana).mark_bar().encode(
      y=alt.Y('dia_semana:N', sort='-x', axis=alt.Axis(labelLimit=200)),
      x=alt.X('qtd:Q', axis=alt.Axis(labelAngle=-45)),
      tooltip=['dia_semana', 'qtd'],
      color=alt.Color('dia_semana:N', scale=lista_cores)

  ).properties(
      title=titulo,
      width=800,
      height=600         
  ).interactive()

  return chart   
# =========================================
def processa_dados_mapa_calor_ano(ano, df):
   
    lista_classificacao = ['Com Vítimas Feridas', 'Com Vítimas Fatais', 'Sem Vítimas']  
    
    df_geral_classificacao = pd.DataFrame(columns=['classificacao','pessoas','mortos','feridos_leves','feridos_graves','ilesos','ignorados','feridos','veiculos'])

    correlacao_classificacao_pessoas = df.groupby('classificacao_acidente')['pessoas'].agg(['count', 'sum'])
    print('pessoas', correlacao_classificacao_pessoas)
    
    correlacao_classificacao_mortos = df.groupby('classificacao_acidente')['mortos'].agg(['count', 'sum'])
    print('mortos',correlacao_classificacao_mortos)
    
    correlacao_classificacao_feridos_leves = df.groupby('classificacao_acidente')['feridos_leves'].agg(['count', 'sum'])
    print('feridos_leves',correlacao_classificacao_feridos_leves)
    
    correlacao_classificacao_feridos_graves = df.groupby('classificacao_acidente')['feridos_graves'].agg(['count', 'sum'])
    print('feridos_graves',correlacao_classificacao_feridos_graves)
    
    correlacao_classificacao_ilesos = df.groupby('classificacao_acidente')['ilesos'].agg(['count', 'sum'])
    print('ilesos', correlacao_classificacao_ilesos)
    
    correlacao_classificacao_ignorados = df.groupby('classificacao_acidente')['ignorados'].agg(['count', 'sum'])
    print('ignorados',correlacao_classificacao_ignorados)
    
    correlacao_classificacao_feridos = df.groupby('classificacao_acidente')['feridos'].agg(['count', 'sum'])
    print('feridos',correlacao_classificacao_feridos)
    
    correlacao_classificacao_veiculos = df.groupby('classificacao_acidente')['veiculos'].agg(['count', 'sum'])
    print('veiculos',correlacao_classificacao_veiculos)

    for (indice,item) in enumerate(lista_classificacao):
        
        # Linha para Classificação
        novo_registro = pd.DataFrame(
            {
             'classificacao': item, 
             'pessoas': [correlacao_classificacao_pessoas.iloc[indice]['sum']], 
             'mortos': [correlacao_classificacao_mortos.iloc[indice]['sum']], 
             'feridos_leves': [correlacao_classificacao_feridos_leves.iloc[indice]['sum']], 
             'feridos_graves': [correlacao_classificacao_feridos_graves.iloc[indice]['sum']], 
             'ilesos': [correlacao_classificacao_ilesos.iloc[indice]['sum']], 
             'ignorados': [correlacao_classificacao_ignorados.iloc[indice]['sum']], 
             'feridos': [correlacao_classificacao_feridos.iloc[indice]['sum']], 
             'veiculos': [correlacao_classificacao_veiculos.iloc[indice]['sum']],      
            }
        )

        df_geral_classificacao = pd.concat([df_geral_classificacao, novo_registro], ignore_index=True)   
    
    return df_geral_classificacao
# =========================================
def salva_mapa_calor_ano(ano, df):    
    nome_arquivo = f'mapa_calor/mapa_calor_classificacao_{str(ano)}.csv'
    df.to_csv(nome_arquivo, index=False)
    print(f'\n\nSalvando arquivo {nome_arquivo}...')
# =========================================

In [26]:
processa_acidentes_geral_dia_semana()

 lista_dias_semanas (7) => ['dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sáb']...

 df_geral_dias_semanas =>        dia_semana    qtd   ano
0         domingo  45193  2007
1         sábado   43461  2007
2         sexta    43047  2007
3         segunda  35779  2007
4         quinta   35311  2007
..            ...    ...   ...
2     sexta-feira  19890  2024
3   segunda-feira  17913  2024
4    quarta-feira  16840  2024
5    quinta-feira  16640  2024
6     terça-feira  16047  2024

[126 rows x 3 columns]


Salvando arquivo acidentes_geral_por_dia_semana...

    dia_semana    qtd   ano
0      domingo  45193  2007
1      domingo  45470  2008
2      domingo  50251  2009
3      domingo  60461  2010
4      domingo  63647  2011
..         ...    ...   ...
121     sábado  27087  2020
122     sábado  27744  2021
123     sábado  29220  2022
124     sábado  29543  2023
125     sábado  20489  2024

[126 rows x 3 columns]

In [38]:
df_acidentes_geral_por_dia_semana = pd.read_csv('acidentes_geral_por_dia_semana.csv', sep=',', encoding="UTF-8") 
df_acidentes_geral_por_dia_semana

df = df_acidentes_geral_por_dia_semana

#df['Nome'] = df['Nome'].str.strip()

df['dia_semana'] = df['dia_semana'].str.strip()
df['dia_semana'] = df['dia_semana'].str.lstrip()

print(df)
df.to_csv('acidentes_geral_por_dia_semana-2.csv')

#df['A'] = df['A'].apply(lambda x: str(x).upper())
df['dia_semana'] = df['dia_semana'].apply(ajusta_dia_semana)
df.to_csv('acidentes_geral_por_dia_semana-3.csv', sep=',', encoding="UTF-8")

    dia_semana    qtd   ano
0      domingo  45193  2007
1      domingo  45470  2008
2      domingo  50251  2009
3      domingo  60461  2010
4      domingo  63647  2011
..         ...    ...   ...
121     sábado  27087  2020
122     sábado  27744  2021
123     sábado  29220  2022
124     sábado  29543  2023
125     sábado  20489  2024

[126 rows x 3 columns]

In [9]:
df_mapa_calor_classificacao_2007 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2007.csv')
df_mapa_calor_classificacao_2008 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2008.csv')
df_mapa_calor_classificacao_2009 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2009.csv')

df_mapa_calor_classificacao_2010 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2010.csv')
df_mapa_calor_classificacao_2011 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2011.csv')
df_mapa_calor_classificacao_2012 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2012.csv')
df_mapa_calor_classificacao_2013 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2013.csv')
df_mapa_calor_classificacao_2014 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2014.csv')
df_mapa_calor_classificacao_2015 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2015.csv')
df_mapa_calor_classificacao_2016 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2016.csv')
df_mapa_calor_classificacao_2017 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2017.csv')
df_mapa_calor_classificacao_2018 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2018.csv')
df_mapa_calor_classificacao_2019 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2019.csv')

df_mapa_calor_classificacao_2020 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2020.csv')
df_mapa_calor_classificacao_2021 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2021.csv')
df_mapa_calor_classificacao_2022 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2022.csv')
df_mapa_calor_classificacao_2023 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2023.csv')
df_mapa_calor_classificacao_2024 = pd.read_csv('mapa_calor/mapa_calor_classificacao_2024.csv')

In [10]:
df_mapa_calor_classificacao_todos = pd.concat(
[
    df_mapa_calor_classificacao_2007, df_mapa_calor_classificacao_2008, df_mapa_calor_classificacao_2009,
    df_mapa_calor_classificacao_2010, df_mapa_calor_classificacao_2011, df_mapa_calor_classificacao_2012,
    df_mapa_calor_classificacao_2013, df_mapa_calor_classificacao_2014, df_mapa_calor_classificacao_2015, 
    df_mapa_calor_classificacao_2016, df_mapa_calor_classificacao_2017, df_mapa_calor_classificacao_2018, 
    df_mapa_calor_classificacao_2019, df_mapa_calor_classificacao_2020, df_mapa_calor_classificacao_2021, 
    df_mapa_calor_classificacao_2022, df_mapa_calor_classificacao_2023, df_mapa_calor_classificacao_2024                    
], axis=0)
df_mapa_calor_classificacao_todos    

contagem_por_classificacao = df_mapa_calor_classificacao_todos.groupby('classificacao').sum().reset_index()
contagem_por_classificacao

#nome_arquivo = f'mapa_calor/mapa_calor_classificacao_geral.csv'
#contagem_por_classificacao.to_csv(nome_arquivo, index=False)
#print(f'\n\nSalvando arquivo {nome_arquivo}...')

,classificacao,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,Com Vítimas Fatais,1565935,53198,663929,216317,517439,139479,880246,1121873
1,Com Vítimas Feridas,188677,66295,27704,23611,47904,28717,51315,121548
2,Sem Vítimas,1205724,0,457075,156919,509401,95111,613994,875877

In [7]:
contagem_por_classificacao_2007 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2007)
contagem_por_classificacao_2008 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2008)
contagem_por_classificacao_2009 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2009)
contagem_por_classificacao_2010 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2010)
contagem_por_classificacao_2011 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2011)
contagem_por_classificacao_2012 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2012)
contagem_por_classificacao_2013 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2013)
contagem_por_classificacao_2014 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2014)
contagem_por_classificacao_2015 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2015)
contagem_por_classificacao_2016 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2016)
contagem_por_classificacao_2017 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2017)
contagem_por_classificacao_2018 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2018)
contagem_por_classificacao_2019 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2019)
contagem_por_classificacao_2020 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2020)
contagem_por_classificacao_2021 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2021)
contagem_por_classificacao_2022 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2022)
contagem_por_classificacao_2023 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2023)
contagem_por_classificacao_2024 = agrupamento_acidentes_por_ano_por_classificacao(df_pessoa_acidentes_2024)

contagem_por_classificacao_2007['ano'] = '2007'
contagem_por_classificacao_2008['ano'] = '2008'
contagem_por_classificacao_2009['ano'] = '2009'
contagem_por_classificacao_2010['ano'] = '2010'
contagem_por_classificacao_2011['ano'] = '2011'
contagem_por_classificacao_2012['ano'] = '2012'
contagem_por_classificacao_2013['ano'] = '2013'
contagem_por_classificacao_2014['ano'] = '2014'
contagem_por_classificacao_2015['ano'] = '2015'
contagem_por_classificacao_2016['ano'] = '2016'
contagem_por_classificacao_2017['ano'] = '2017'
contagem_por_classificacao_2018['ano'] = '2018'
contagem_por_classificacao_2019['ano'] = '2019'
contagem_por_classificacao_2020['ano'] = '2020'
contagem_por_classificacao_2021['ano'] = '2021'
contagem_por_classificacao_2022['ano'] = '2022'
contagem_por_classificacao_2023['ano'] = '2023'
contagem_por_classificacao_2024['ano'] = '2024'

acidentes_por_classificacao_concatenados = pd.concat(
[
  contagem_por_classificacao_2007, contagem_por_classificacao_2008, contagem_por_classificacao_2009,
  contagem_por_classificacao_2010, contagem_por_classificacao_2011, contagem_por_classificacao_2012,
  contagem_por_classificacao_2013, contagem_por_classificacao_2014, contagem_por_classificacao_2015,
  contagem_por_classificacao_2016, contagem_por_classificacao_2017, contagem_por_classificacao_2018,
  contagem_por_classificacao_2019, contagem_por_classificacao_2020, contagem_por_classificacao_2021,
  contagem_por_classificacao_2022, contagem_por_classificacao_2023, contagem_por_classificacao_2024

], axis=0)

lista_classificacoes_antes = acidentes_por_classificacao_concatenados['classificacao_acidente'].unique()
print(f'lista_classificacoes_antes => {lista_classificacoes_antes}')

lista_classificacoes_depois = [item.rstrip() for item in lista_classificacoes_antes]
lista_classificacoes_depois.remove('(null)')

print(f'lista_classificacoes_depois => {lista_classificacoes_depois}')

lista_sem_duplicacacoes = list(set(lista_classificacoes_depois))
print(f'lista_sem_duplicacacoes => {lista_sem_duplicacacoes}')


lista_classificacoes = lista_sem_duplicacacoes

print(f'lista_classificacoes => {lista_classificacoes} ')

df_classificacao = acidentes_por_classificacao_concatenados
df_geral_classificacao = pd.DataFrame(columns=['classificacao_acidente','qtd','ano'])

for item in lista_classificacoes:
  df_filtrado_classificacao = df_classificacao[(df_classificacao['classificacao_acidente'] == item)]
  df_geral_classificacao = pd.concat([df_geral_classificacao, df_filtrado_classificacao], ignore_index=True)

df_geral_classificacao

lista_classificacoes_antes => ['Sem Vítimas        ' 'Com Vítimas Feridas' 'Com Vítimas Fatais '
 'Ignorado           ' '(null)' 'Sem Vítimas' 'Com Vítimas Fatais'
 'Ignorado']
lista_classificacoes_depois => ['Sem Vítimas', 'Com Vítimas Feridas', 'Com Vítimas Fatais', 'Ignorado', 'Sem Vítimas', 'Com Vítimas Fatais', 'Ignorado']
lista_sem_duplicacacoes => ['Com Vítimas Fatais', 'Ignorado', 'Com Vítimas Feridas', 'Sem Vítimas']
lista_classificacoes => ['Com Vítimas Fatais', 'Ignorado', 'Com Vítimas Feridas', 'Sem Vítimas']

   classificacao_acidente     qtd   ano
0      Com Vítimas Fatais   16711  2016
1      Com Vítimas Fatais   18508  2017
2      Com Vítimas Fatais   16531  2018
3      Com Vítimas Fatais   16543  2019
4      Com Vítimas Fatais   15303  2020
5      Com Vítimas Fatais   16633  2021
6      Com Vítimas Fatais   17247  2022
7      Com Vítimas Fatais   18254  2023
8      Com Vítimas Fatais   12517  2024
9                Ignorado    1878  2016
10    Com Vítimas Feridas  111833  2007
11    Com Vítimas Feridas  120499  2008
12    Com Vítimas Feridas  133950  2009
13    Com Vítimas Feridas  151082  2010
14    Com Vítimas Feridas  157836  2011
15    Com Vítimas Feridas  153102  2012
16    Com Vítimas Feridas  155771  2013
17    Com Vítimas Feridas  150742  2014
18    Com Vítimas Feridas  136605  2015
19    Com Vítimas Feridas  132806  2016
20    Com Vítimas Feridas  139263  2017
21    Com Vítimas Feridas  129270  2018
22    Com Vítimas Feridas  133672  2019
23    Com Vítimas Feridas  121470  2020
24    Com Vítimas Feridas  124127  2021
25    Com Vítimas Feridas  127233  2022
26    Com Vítimas Feridas  139581  2023
27    Com Vítimas Feridas   97856  2024
28            Sem Vítimas   64864  2016
29            Sem Vítimas   66462  2017
30            Sem Vítimas   34257  2018
31            Sem Vítimas   25880  2019
32            Sem Vítimas   25475  2020
33            Sem Vítimas   25527  2021
34            Sem Vítimas   26332  2022
35            Sem Vítimas   25517  2023
36            Sem Vítimas   17750  2024

In [8]:
# processa arquivos
df_acidentes_uf_geral = processa_acidentes_geral_ufs()
df_acidentes_tipo_geral = processa_acidentes_geral_tipo()
df_acidentes_br_geral = processa_acidentes_geral_br()
df_acidentes_causa_geral = processa_acidentes_geral_causa()
df_acidentes_classificacao_geral = processa_acidentes_geral_classificacao()
df_acidentes_fasedia_geral = processa_acidentes_geral_fase_dia()
df_acidentes_condicao_geral = processa_acidentes_geral_condicao_metereologica()

Salvando arquivo acidentes_geral_por_uf...


Salvando arquivo acidentes_geral_por_tipo.csv...


Salvando arquivo acidentes_geral_por_br.csv...


Salvando arquivo acidentes_geral_por_causa.csv...
lista_classificacoes_antes => ['Sem Vítimas        ' 'Com Vítimas Feridas' 'Com Vítimas Fatais '
 'Ignorado           ' '(null)' 'Sem Vítimas' 'Com Vítimas Fatais'
 'Ignorado']
lista_classificacoes_depois => ['Sem Vítimas', 'Com Vítimas Feridas', 'Com Vítimas Fatais', 'Ignorado', 'Sem Vítimas', 'Com Vítimas Fatais', 'Ignorado']
lista_sem_duplicacacoes => ['Com Vítimas Fatais', 'Ignorado', 'Com Vítimas Feridas', 'Sem Vítimas']
lista_classificacoes => ['Com Vítimas Fatais', 'Ignorado', 'Com Vítimas Feridas', 'Sem Vítimas']


Salvando arquivo acidentes_geral_por_classificacao.csv...


Salvando arquivo acidentes_geral_por_fase_dia.csv...


Salvando arquivo acidentes_geral_por_condicao_metereologica.csv...

In [19]:
df_filtrado_causa = df_acidentes_causa_geral[(df_acidentes_causa_geral['ano'] == '2023')]
df_filtrado_causa

                               causa_acidente    qtd   ano
100                          Animais na Pista   2579  2023
132                   Velocidade Incompatível  10926  2023
152                         Condutor Dormindo   5421  2023
160                        Pista Escorregadia   1199  2023
168                    Ultrapassagem Indevida   6150  2023
180   Avarias e/ou desgaste excessivo no pneu   2789  2023
200  Objeto estático sobre o leito carroçável    755  2023

In [13]:
import altair as alt
from vega_datasets import data

source = data.cars()
source

,Name,Miles_per_Gallon,Cylinders,Displacement,Horsepower,Weight_in_lbs,Acceleration,Year,Origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,1970-01-01,USA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,1970-01-01,USA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,1970-01-01,USA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,1970-01-01,USA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,1970-01-01,USA
...,...,...,...,...,...,...,...,...,...
401,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,1982-01-01,USA
402,vw pickup,44.0,4,97.0,52.0,2130,24.6,1982-01-01,Europe
403,dodge rampage,32.0,4,135.0,84.0,2295,11.6,1982-01-01,USA
404,ford ranger,28.0,4,120.0,79.0,2625,18.6,1982-01-01,USA
405,chevy s-10,31.0,4,119.0,82.0,2720,19.4,1982-01-01,USA

In [14]:
alt.Chart(source).mark_circle().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='Origin:N'
).properties(
    width=150,
    height=150
).repeat(
    row=['Horsepower', 'Acceleration', 'Miles_per_Gallon'],
    column=['Miles_per_Gallon', 'Acceleration', 'Horsepower']
).interactive()

alt.RepeatChart(...)

In [15]:
df_mapa_calor_classificacao_2024

,classificacao,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,Com Vítimas Feridas,11862,3992,1459,1350,3121,2595,2809,8583
1,Com Vítimas Fatais,95117,0,40174,11908,33731,12043,52082,72148
2,Sem Vítimas,16840,0,0,0,13235,4515,0,14556

In [19]:
alt.Chart(df_mapa_calor_classificacao_2024).mark_circle().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='classificacao:N'
).properties(
    width=150,
    height=150
).repeat(
    row=['pessoas', 'mortos','feridos'],
    column=['feridos_leves', 'feridos_graves', 'ilesos', 'veiculos']
).interactive()

alt.RepeatChart(...)

In [37]:
    df_envolvidos = pd.read_csv('datasets-old/correlacao_acidentes_geral.csv')

    # Define os dados
    dados = df_envolvidos.set_index('tipo').T.reset_index().melt(id_vars='index', var_name='tipo', value_name='value')

    # Cria o gráfico de calor
    heatmap = alt.Chart(dados).mark_rect().encode(
        x=alt.X('index:O', title=None, axis=alt.Axis(orient='top')),  # Define a orientação do eixo x como 'top'
        y=alt.Y('tipo:O', title=None),
        color=alt.Color('value:Q', scale=alt.Scale(scheme='yellowgreenblue')),
    )

    # Adiciona o texto dentro de cada célula com o valor real e ajusta a cor do texto
    text = alt.Chart(dados).mark_text(baseline='middle', fontSize=10).encode(
        x='index:O',
        y='tipo:O',
        text=alt.Text('value:Q', format='.0f'),
        color=alt.condition(
            alt.datum['value'] > (dados['value'].max() - dados['value'].min()) / 2,
            alt.value('white'),
            alt.value('black')
        )
    )

    # Combina o gráfico de calor com o texto
    heatmap_with_text = (heatmap + text).properties(
        width=800,
        height=600,
        title=f'Mapa de Calor dos Envolvidos nos acidentes (aaa)'
    )

    # Exibe o gráfico
    heatmap_with_text

alt.LayerChart(...)

In [38]:
    df_envolvidos = pd.read_csv('dados-teste.csv')

    # Define os dados
    dados = df_envolvidos.set_index('classificacao').T.reset_index().melt(id_vars='index', var_name='classificacao', value_name='value')

    # Cria o gráfico de calor
    heatmap = alt.Chart(dados).mark_rect().encode(
        x=alt.X('index:O', title=None, axis=alt.Axis(orient='top')),  # Define a orientação do eixo x como 'top'
        y=alt.Y('classificacao:O', title=None),
        color=alt.Color('value:Q', scale=alt.Scale(scheme='yellowgreenblue')),
    )

    # Adiciona o texto dentro de cada célula com o valor real e ajusta a cor do texto
    text = alt.Chart(dados).mark_text(baseline='middle', fontSize=10).encode(
        x='index:O',
        y='classificacao:O',
        text=alt.Text('value:Q', format='.0f'),
        color=alt.condition(
            alt.datum['value'] > (dados['value'].max() - dados['value'].min()) / 2,
            alt.value('white'),
            alt.value('black')
        )
    )

    # Combina o gráfico de calor com o texto
    heatmap_with_text = (heatmap + text).properties(
        width=800,
        height=600,
        title=f'Mapa de Calor dos Envolvidos nos acidentes (aaa)'
    )

    # Exibe o gráfico
    heatmap_with_text

alt.LayerChart(...)

In [40]:
df = df_por_ocorrencia_2023

correlacao_classificacao_pessoas = df.groupby('classificacao_acidente')['pessoas'].agg(['count', 'sum'])
print(type(correlacao_classificacao_pessoas), correlacao_classificacao_pessoas)

correlacao_classificacao_mortos = df.groupby('classificacao_acidente')['mortos'].agg(['count', 'sum'])
print(correlacao_classificacao_mortos)

correlacao_classificacao_feridos_leves = df.groupby('classificacao_acidente')['feridos_leves'].agg(['count', 'sum'])
print(correlacao_classificacao_feridos_leves)

correlacao_classificacao_feridos_graves = df.groupby('classificacao_acidente')['feridos_graves'].agg(['count', 'sum'])
print(correlacao_classificacao_feridos_graves)

correlacao_classificacao_ilesos = df.groupby('classificacao_acidente')['ilesos'].agg(['count', 'sum'])
print(correlacao_classificacao_ilesos)

correlacao_classificacao_ignorados = df.groupby('classificacao_acidente')['ignorados'].agg(['count', 'sum'])
print(correlacao_classificacao_ignorados)

correlacao_classificacao_feridos = df.groupby('classificacao_acidente')['feridos'].agg(['count', 'sum'])
print(correlacao_classificacao_feridos)

correlacao_classificacao_veiculos = df.groupby('classificacao_acidente')['veiculos'].agg(['count', 'sum'])
print(correlacao_classificacao_veiculos)

<class 'pandas.core.frame.DataFrame'>                         count     sum
classificacao_acidente
Com Vítimas Fatais       4858   17339
Com Vítimas Feridas     51942  135585
Sem Vítimas             10963   24281
                        count   sum
classificacao_acidente
Com Vítimas Fatais       4858  5627
Com Vítimas Feridas     51942     0
Sem Vítimas             10963     0
                        count    sum
classificacao_acidente
Com Vítimas Fatais       4858   2240
Com Vítimas Feridas     51942  57266
Sem Vítimas             10963      0
                        count    sum
classificacao_acidente
Com Vítimas Fatais       4858   1864
Com Vítimas Feridas     51942  17089
Sem Vítimas             10963      0
                        count    sum
classificacao_acidente
Com Vítimas Fatais       4858   4893
Com Vítimas Feridas     51942  48012
Sem Vítimas             10963  19162
                        count    sum
classificacao_acidente
Com Vítimas Fatais       4858   3630
Com Vítimas Feridas     51942  17214
Sem Vítimas             10963   6355
                        count    sum
classificacao_acidente
Com Vítimas Fatais       4858   4104
Com Vítimas Feridas     51942  74355
Sem Vítimas             10963      0
                        count     sum
classificacao_acidente
Com Vítimas Fatais       4858   12175
Com Vítimas Feridas     51942  102524
Sem Vítimas             10963   20683

In [41]:
df_geral_classificacao = pd.DataFrame(columns=['classificacao','pessoas','mortos','feridos_leves','feridos_graves','ilesos','ignorados','feridos','veiculos'])
df_geral_classificacao

Empty DataFrame
Columns: [classificacao, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos]
Index: []

In [6]:
processa_acidentes_geral_dia_semana()

 lista_dias_semanas (7) => ['domingo', 'Segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado']...


Salvando arquivo acidentes_geral_por_dia_semana...

       dia_semana    qtd   ano
0         domingo  37737  2017
1         domingo  29951  2018
2         domingo  29679  2019
3         domingo  26711  2020
4         domingo  27559  2021
5         domingo  29183  2022
6         domingo  30585  2023
7         domingo  20307  2024
8   segunda-feira  30056  2017
9   segunda-feira  24023  2018
10  segunda-feira  23639  2019
11  segunda-feira  21625  2020
12  segunda-feira  22157  2021
13  segunda-feira  22904  2022
14  segunda-feira  25078  2023
15  segunda-feira  17913  2024
16    terça-feira  26696  2017
17    terça-feira  22022  2018
18    terça-feira  21689  2019
19    terça-feira  19848  2020
20    terça-feira  20026  2021
21    terça-feira  20469  2022
22    terça-feira  22459  2023
23    terça-feira  16047  2024
24   quarta-feira  27532  2017
25   quarta-feira  22811  2018
26   quarta-feira  21720  2019
27   quarta-feira  20590  2020
28   quarta-feira  20881  2021
29   quarta-feira  21210  2022
30   quarta-feira  23380  2023
31   quarta-feira  16840  2024
32   quinta-feira  29693  2017
33   quinta-feira  23584  2018
34   quinta-feira  22871  2019
35   quinta-feira  21125  2020
36   quinta-feira  21421  2021
37   quinta-feira  21281  2022
38   quinta-feira  24167  2023
39   quinta-feira  16640  2024
40    sexta-feira  34563  2017
41    sexta-feira  27902  2018
42    sexta-feira  27459  2019
43    sexta-feira  25266  2020
44    sexta-feira  26506  2021
45    sexta-feira  26548  2022
46    sexta-feira  28143  2023
47    sexta-feira  19890  2024
48         sábado  37960  2017
49         sábado  29768  2018
50         sábado  29047  2019
51         sábado  27087  2020
52         sábado  27744  2021
53         sábado  29220  2022
54         sábado  29543  2023
55         sábado  20489  2024

In [22]:
contagem_por_dia_semana_2023 = agrupamento_acidentes_por_ano_por_dia_semana(df_pessoa_acidentes_2023)
contagem_por_dia_semana_2023

      dia_semana    qtd
0        domingo  30585
1         sábado  29543
2    sexta-feira  28143
3  segunda-feira  25078
4   quinta-feira  24167
5   quarta-feira  23380
6    terça-feira  22459

In [27]:
grafico1 = gera_grafico_por_dia_semana('2023', contagem_por_dia_semana_2023)
grafico1

alt.Chart(...)

In [34]:
df_acidentes_geral_por_dia_semana = pd.read_csv('acidentes_geral_por_dia_semana.csv', sep=',', encoding="UTF-8") 
df_acidentes_geral_por_dia_semana

       dia_semana    qtd   ano
0         Domingo  37737  2017
1         Domingo  29951  2018
2         Domingo  29679  2019
3         Domingo  26711  2020
4         Domingo  27559  2021
5         Domingo  29183  2022
6         Domingo  30585  2023
7         Domingo  20307  2024
8   Segunda-feira  30056  2017
9   Segunda-feira  24023  2018
10  Segunda-feira  23639  2019
11  Segunda-feira  21625  2020
12  Segunda-feira  22157  2021
13  Segunda-feira  22904  2022
14  Segunda-feira  25078  2023
15  Segunda-feira  17913  2024
16    Terça-feira  26696  2017
17    Terça-feira  22022  2018
18    Terça-feira  21689  2019
19    Terça-feira  19848  2020
20    Terça-feira  20026  2021
21    Terça-feira  20469  2022
22    Terça-feira  22459  2023
23    Terça-feira  16047  2024
24   Quarta-feira  27532  2017
25   Quarta-feira  22811  2018
26   Quarta-feira  21720  2019
27   Quarta-feira  20590  2020
28   Quarta-feira  20881  2021
29   Quarta-feira  21210  2022
30   Quarta-feira  23380  2023
31   Quarta-feira  16840  2024
32   Quinta-feira  29693  2017
33   Quinta-feira  23584  2018
34   Quinta-feira  22871  2019
35   Quinta-feira  21125  2020
36   Quinta-feira  21421  2021
37   Quinta-feira  21281  2022
38   Quinta-feira  24167  2023
39   Quinta-feira  16640  2024
40    Sexta-feira  34563  2017
41    Sexta-feira  27902  2018
42    Sexta-feira  27459  2019
43    Sexta-feira  25266  2020
44    Sexta-feira  26506  2021
45    Sexta-feira  26548  2022
46    Sexta-feira  28143  2023
47    Sexta-feira  19890  2024
48         Sábado  37960  2017
49         Sábado  29768  2018
50         Sábado  29047  2019
51         Sábado  27087  2020
52         Sábado  27744  2021
53         Sábado  29220  2022
54         Sábado  29543  2023
55         Sábado  20489  2024